"""add api.airlines

Revision ID: 3f7f41318c02
Revises: be4be75beefe
Create Date: 2026-06-27 23:11:35.695854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7f41318c02'
down_revision: Union[str, Sequence[str], None] = 'be4be75beefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('airline_name', sa.String(), nullable=False),
    sa.Column('icao', sa.String(), nullable=False),
    sa.Column('iata', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='api'
    )
    op.create_index(op.f('ix_api_airline_airline_name'), 'airline', ['airline_name'], unique=False, schema='api')
    op.create_index(op.f('ix_api_airline_iata'), 'airline', ['iata'], unique=False, schema='api')
    op.create_index(op.f('ix_api_airline_icao'), 'airline', ['icao'], unique=False, schema='api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_airline_icao'), table_name='airline', schema='api')
    op.drop_index(op.f('ix_api_airline_iata'), table_name='airline', schema='api')
    op.drop_index(op.f('ix_api_airline_airline_name'), table_name='airline', schema='api')
    op.drop_table('airline', schema='api')
    # ### end Alembic commands ###
