"""create icao tables

Revision ID: a46c19b14424
Revises: f6a7b8c9d0e1
Create Date: 2026-06-28 01:59:38.030010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46c19b14424'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # icao schema hosts the legacy ICAO + ICAO-API reference/reporting tables.
    op.execute('CREATE SCHEMA IF NOT EXISTS "icao"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accidents',
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('StateOfOccurrence', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('Model', sa.String(), nullable=True),
    sa.Column('Registration', sa.String(), nullable=True),
    sa.Column('Operator', sa.String(), nullable=True),
    sa.Column('StateOfOperator', sa.String(), nullable=True),
    sa.Column('StateOfRegistry', sa.String(), nullable=True),
    sa.Column('FlightPhase', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('Fatalities', sa.Integer(), nullable=True),
    sa.Column('Over2250', sa.Boolean(), nullable=True),
    sa.Column('Over5700', sa.Boolean(), nullable=True),
    sa.Column('ScheduledCommercial', sa.Boolean(), nullable=True),
    sa.Column('InjuryLevel', sa.String(), nullable=True),
    sa.Column('TypeDesignator', sa.String(), nullable=True),
    sa.Column('Helicopter', sa.Boolean(), nullable=True),
    sa.Column('Airplane', sa.Boolean(), nullable=True),
    sa.Column('Engines', sa.Integer(), nullable=True),
    sa.Column('EngineType', sa.String(), nullable=True),
    sa.Column('Official', sa.String(), nullable=True),
    sa.Column('Risk', sa.String(), nullable=True),
    sa.Column('OccCats', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Date', 'Location', 'Model', 'Registration', 'StateOfOccurrence', name='uq_icao_accidents_Date_Location_Model_Registration_StateOfOccur'),
    schema='icao'
    )
    op.create_table('aerodrome_locations',
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('airportName', sa.String(), nullable=True),
    sa.Column('cityName', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('airportCode', sa.String(), nullable=True),
    sa.Column('geometry', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airportCode', 'countryCode', name='uq_icao_aerodrome_locations_airportCode_countryCode'),
    schema='icao'
    )
    op.create_table('aerodrome_statistics',
    sa.Column('State', sa.String(length=3), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Departures', sa.Integer(), nullable=True),
    sa.Column('All_Active_Aerodromes', sa.Integer(), nullable=True),
    sa.Column('Int_Active_Aerodromes', sa.Integer(), nullable=True),
    sa.Column('Int_Departures', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_aerodrome_statistics_State'), 'aerodrome_statistics', ['State'], unique=True, schema='icao')
    op.create_table('aircraft_types',
    sa.Column('manufacturer_code', sa.String(), nullable=True),
    sa.Column('model_no', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('engine_count', sa.String(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.Column('aircraft_desc', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('wtc', sa.String(), nullable=True),
    sa.Column('wtg', sa.String(), nullable=True),
    sa.Column('tdesig', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_code', 'model_no', 'model_name', 'model_version', name='uq_icao_aircraft_types_manufacturer_code_model_no_model_name_mo'),
    schema='icao'
    )
    op.create_table('airport_pbn_implementation',
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('airportName', sa.String(), nullable=True),
    sa.Column('cityName', sa.String(), nullable=True),
    sa.Column('airportCode', sa.String(), nullable=True),
    sa.Column('nb_instr_vg_runways', sa.Integer(), nullable=True),
    sa.Column('nb_instr_runways', sa.Integer(), nullable=True),
    sa.Column('pbn_implementation', sa.Integer(), nullable=True),
    sa.Column('pc_pbn_lnav', sa.Integer(), nullable=True),
    sa.Column('pc_pbn_lnavvnav', sa.Integer(), nullable=True),
    sa.Column('pc_pbn_lpv', sa.Integer(), nullable=True),
    sa.Column('pc_pbn_rnpar', sa.Integer(), nullable=True),
    sa.Column('pc_pbn_unknown', sa.Integer(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('IsInternational', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airportCode'),
    schema='icao'
    )
    op.create_table('asiap_prioritization',
    sa.Column('iso_2_code', sa.String(length=2), nullable=True),
    sa.Column('iso_3_code', sa.String(length=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('UN_numerical_code', sa.String(), nullable=True),
    sa.Column('UN_region', sa.String(), nullable=True),
    sa.Column('UN_state_name', sa.String(), nullable=True),
    sa.Column('UN_state_name_html', sa.String(), nullable=True),
    sa.Column('ro', sa.String(), nullable=True),
    sa.Column('wgi_year', sa.Integer(), nullable=True),
    sa.Column('gdp', sa.Float(), nullable=True),
    sa.Column('gdp_pcapita', sa.Float(), nullable=True),
    sa.Column('corruption', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('operations_ei', sa.Float(), nullable=True),
    sa.Column('support_ei', sa.Float(), nullable=True),
    sa.Column('airnavigation_ei', sa.Float(), nullable=True),
    sa.Column('operations_margin', sa.Float(), nullable=True),
    sa.Column('support_margin', sa.Float(), nullable=True),
    sa.Column('airnavigation_margin', sa.Float(), nullable=True),
    sa.Column('isSSC', sa.Boolean(), nullable=True),
    sa.Column('SSC_area', sa.String(), nullable=True),
    sa.Column('operations_index', sa.Float(), nullable=True),
    sa.Column('support_index', sa.Float(), nullable=True),
    sa.Column('airnavigation_index', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UN_numerical_code'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_asiap_prioritization_iso_3_code'), 'asiap_prioritization', ['iso_3_code'], unique=False, schema='icao')
    op.create_index(op.f('ix_icao_asiap_prioritization_ro'), 'asiap_prioritization', ['ro'], unique=False, schema='icao')
    op.create_table('caahr',
    sa.Column('iso_2_code', sa.String(length=2), nullable=True),
    sa.Column('iso_3_code', sa.String(length=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('UN_numerical_code', sa.String(), nullable=True),
    sa.Column('UN_region', sa.String(), nullable=True),
    sa.Column('UN_state_name', sa.String(), nullable=True),
    sa.Column('UN_state_name_html', sa.String(), nullable=True),
    sa.Column('ro', sa.String(), nullable=True),
    sa.Column('aeroplane_CAT_ops', sa.Integer(), nullable=True),
    sa.Column('aeroplane_used_CAT', sa.Integer(), nullable=True),
    sa.Column('approved_maintenance', sa.Integer(), nullable=True),
    sa.Column('ifr_aerodromes', sa.Integer(), nullable=True),
    sa.Column('atc_training_org', sa.Integer(), nullable=True),
    sa.Column('atc_licenses', sa.Integer(), nullable=True),
    sa.Column('fto', sa.Integer(), nullable=True),
    sa.Column('mto', sa.Integer(), nullable=True),
    sa.Column('private_licences', sa.Integer(), nullable=True),
    sa.Column('professional_licences', sa.Integer(), nullable=True),
    sa.Column('maintenance_licences', sa.Integer(), nullable=True),
    sa.Column('total_air', sa.Integer(), nullable=True),
    sa.Column('total_aga', sa.Integer(), nullable=True),
    sa.Column('total_ans', sa.Integer(), nullable=True),
    sa.Column('total_pel', sa.Integer(), nullable=True),
    sa.Column('total_ops', sa.Integer(), nullable=True),
    sa.Column('isOriginalSurvey', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UN_state_name'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_caahr_iso_2_code'), 'caahr', ['iso_2_code'], unique=False, schema='icao')
    op.create_index(op.f('ix_icao_caahr_iso_3_code'), 'caahr', ['iso_3_code'], unique=False, schema='icao')
    op.create_table('connections',
    sa.Column('State_A', sa.String(length=3), nullable=True),
    sa.Column('Name_A', sa.String(), nullable=True),
    sa.Column('State_B', sa.String(length=3), nullable=True),
    sa.Column('Name_B', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Flights', sa.Integer(), nullable=True),
    sa.Column('State_A_Carrier_Flights', sa.Integer(), nullable=True),
    sa.Column('State_B_Carrier_Flights', sa.Integer(), nullable=True),
    sa.Column('Other_State_Carrier_Flights', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('State_A', 'State_B', 'Year', name='uq_icao_connections_State_A_State_B_Year'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_connections_State_A'), 'connections', ['State_A'], unique=False, schema='icao')
    op.create_table('countries_iso',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alpha3_code', sa.String(length=3), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha3_code'),
    sa.UniqueConstraint('name'),
    schema='icao'
    )
    op.create_table('finances',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('air_carrier', sa.String(length=255), nullable=False),
    sa.Column('financial_category', sa.String(length=255), nullable=False),
    sa.Column('main_account', sa.String(length=255), nullable=False),
    sa.Column('sub_account', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=32, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'air_carrier', 'financial_category', 'main_account', 'sub_account', name='uq_icao_finances_year_air_carrier_financial_category_main_accou'),
    schema='icao'
    )
    op.create_table('icao_member_states',
    sa.Column('RASG', sa.String(), nullable=True),
    sa.Column('iso_2_code', sa.String(length=2), nullable=True),
    sa.Column('iso_3_code', sa.String(length=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('UN_numerical_code', sa.String(), nullable=True),
    sa.Column('UN_region', sa.String(), nullable=True),
    sa.Column('UN_state_name', sa.String(), nullable=True),
    sa.Column('UN_state_name_html', sa.String(), nullable=True),
    sa.Column('ICAO_regional_office', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UN_numerical_code'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_icao_member_states_RASG'), 'icao_member_states', ['RASG'], unique=False, schema='icao')
    op.create_index(op.f('ix_icao_icao_member_states_iso_3_code'), 'icao_member_states', ['iso_3_code'], unique=False, schema='icao')
    op.create_table('incidents',
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('StateOfOccurrence', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('Model', sa.String(), nullable=True),
    sa.Column('Registration', sa.String(), nullable=True),
    sa.Column('Operator', sa.String(), nullable=True),
    sa.Column('StateOfOperator', sa.String(), nullable=True),
    sa.Column('StateOfRegistry', sa.String(), nullable=True),
    sa.Column('FlightPhase', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('Fatalities', sa.Integer(), nullable=True),
    sa.Column('Over2250', sa.Boolean(), nullable=True),
    sa.Column('Over5700', sa.Boolean(), nullable=True),
    sa.Column('ScheduledCommercial', sa.Boolean(), nullable=True),
    sa.Column('InjuryLevel', sa.String(), nullable=True),
    sa.Column('TypeDesignator', sa.String(), nullable=True),
    sa.Column('Helicopter', sa.Boolean(), nullable=True),
    sa.Column('Airplane', sa.Boolean(), nullable=True),
    sa.Column('Engines', sa.Integer(), nullable=True),
    sa.Column('EngineType', sa.String(), nullable=True),
    sa.Column('Official', sa.String(), nullable=True),
    sa.Column('OccCats', sa.String(), nullable=True),
    sa.Column('Risk', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Date', 'Location', 'Model', 'Registration', 'StateOfOccurrence', name='uq_icao_incidents_Date_Location_Model_Registration_StateOfOccur'),
    schema='icao'
    )
    op.create_table('international_aerodromes',
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('airportName', sa.String(), nullable=True),
    sa.Column('cityName', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('airportCode', sa.String(), nullable=True),
    sa.Column('geometry', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airportCode', 'countryCode', name='uq_icao_international_aerodromes_airportCode_countryCode'),
    schema='icao'
    )
    op.create_table('international_airport_safety',
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('airportName', sa.String(), nullable=True),
    sa.Column('cityName', sa.String(), nullable=True),
    sa.Column('airportCode', sa.String(), nullable=True),
    sa.Column('airnavigation_ei', sa.Float(), nullable=True),
    sa.Column('airnavigation_margin', sa.Float(), nullable=True),
    sa.Column('hasFullInstrumentVG', sa.Boolean(), nullable=True),
    sa.Column('hasInstrumentVG', sa.Boolean(), nullable=True),
    sa.Column('hasInstrument', sa.Boolean(), nullable=True),
    sa.Column('IMC', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('TerrainAbove300m', sa.Float(), nullable=True),
    sa.Column('TerrainAbove600m', sa.Float(), nullable=True),
    sa.Column('TerrainAbove900m', sa.Float(), nullable=True),
    sa.Column('hasIntersectingRWYs', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airportCode'),
    schema='icao'
    )
    op.create_table('last_update',
    sa.Column('last_update', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='icao'
    )
    op.create_table('location_indicators',
    sa.Column('terr_code', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('icao_code', sa.String(), nullable=True),
    sa.Column('aftn', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('lat_dms', sa.String(), nullable=True),
    sa.Column('long_dms', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('codcoun', sa.String(), nullable=True),
    sa.Column('iata_code', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='icao'
    )
    op.create_table('manufacturers',
    sa.Column('manufacturer_code', sa.String(), nullable=False),
    sa.Column('types', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_code'),
    schema='icao'
    )
    op.create_table('metar_provider_location',
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('airportName', sa.String(), nullable=True),
    sa.Column('airportCode', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airportCode'),
    schema='icao'
    )
    op.create_table('operational_aerodrome_information',
    sa.Column('FIRname', sa.String(), nullable=True),
    sa.Column('FIRcode', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('proc_runways', sa.Integer(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('iatacode', sa.String(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('airportCode', sa.String(), nullable=True),
    sa.Column('airportName', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airportCode'),
    schema='icao'
    )
    op.create_table('operator_risk_profiles',
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('operatorName', sa.String(), nullable=True),
    sa.Column('operatorCode', sa.String(), nullable=True),
    sa.Column('av_fleet_age', sa.Float(), nullable=True),
    sa.Column('aircraft', sa.Integer(), nullable=True),
    sa.Column('models', sa.Integer(), nullable=True),
    sa.Column('aircraft_over_25y', sa.Integer(), nullable=True),
    sa.Column('routes', sa.Integer(), nullable=True),
    sa.Column('annual_flights', sa.Integer(), nullable=True),
    sa.Column('annual_international_flights', sa.Integer(), nullable=True),
    sa.Column('is_iosa_certified', sa.Boolean(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('accidents_5y', sa.Integer(), nullable=True),
    sa.Column('fatalaccidents_5y', sa.Integer(), nullable=True),
    sa.Column('connections', sa.Integer(), nullable=True),
    sa.Column('destinations', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operatorCode', 'aircraft', 'models', name='uq_icao_operator_risk_profiles_operatorCode_aircraft_models'),
    schema='icao'
    )
    op.create_table('operator_statistics',
    sa.Column('State', sa.String(length=3), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Flights', sa.Integer(), nullable=True),
    sa.Column('Int_Flights', sa.Integer(), nullable=True),
    sa.Column('All_Active_Operators', sa.Integer(), nullable=True),
    sa.Column('Int_Active_Operators', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_operator_statistics_State'), 'operator_statistics', ['State'], unique=True, schema='icao')
    op.create_table('operators',
    sa.Column('countryName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('operatorName', sa.String(), nullable=True),
    sa.Column('operatorCode', sa.String(), nullable=True),
    sa.Column('telephonyName', sa.String(), nullable=True),
    sa.Column('LastModified', sa.String(), nullable=True),
    sa.Column('AIRAC', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operatorCode'),
    schema='icao'
    )
    op.create_table('passengersflow',
    sa.Column('from_city', sa.String(), nullable=False),
    sa.Column('to_city', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('air_carrier', sa.String(), nullable=False),
    sa.Column('aircraft_type', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=True),
    sa.Column('from_territory', sa.String(), nullable=True),
    sa.Column('to_territory', sa.String(), nullable=True),
    sa.Column('prt', sa.Integer(), nullable=True),
    sa.Column('number_of_flights', sa.Integer(), nullable=True),
    sa.Column('seats_available', sa.Integer(), nullable=True),
    sa.Column('average_seats_available', sa.Integer(), nullable=True),
    sa.Column('passenger_occupancy_factor', sa.Float(), nullable=True),
    sa.Column('average_payload_capacity', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_city', 'to_city', 'year', 'air_carrier', 'aircraft_type', name='uq_icao_passengersflow_from_city_to_city_year_air_carrier_aircr'),
    schema='icao'
    )
    op.create_table('safety_related_occurrences',
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('StateOfOccurrence', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('Model', sa.String(), nullable=True),
    sa.Column('Registration', sa.String(), nullable=True),
    sa.Column('Operator', sa.String(), nullable=True),
    sa.Column('StateOfOperator', sa.String(), nullable=True),
    sa.Column('StateOfRegistry', sa.String(), nullable=True),
    sa.Column('FlightPhase', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('Fatalities', sa.Integer(), nullable=True),
    sa.Column('Over2250', sa.Boolean(), nullable=True),
    sa.Column('Over5700', sa.Boolean(), nullable=True),
    sa.Column('ScheduledCommercial', sa.Boolean(), nullable=True),
    sa.Column('InjuryLevel', sa.String(), nullable=True),
    sa.Column('TypeDesignator', sa.String(), nullable=True),
    sa.Column('Helicopter', sa.Boolean(), nullable=True),
    sa.Column('Airplane', sa.Boolean(), nullable=True),
    sa.Column('Engines', sa.Integer(), nullable=True),
    sa.Column('EngineType', sa.String(), nullable=True),
    sa.Column('Official', sa.String(), nullable=True),
    sa.Column('OccCats', sa.String(), nullable=True),
    sa.Column('Risk', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Date', 'Location', 'Model', 'Registration', 'StateOfOccurrence', name='uq_icao_safety_related_occurrences_Date_Location_Model_Registra'),
    schema='icao'
    )
    op.create_table('ssp_foundation',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('State', sa.String(length=3), nullable=True),
    sa.Column('OverallSSPFoundation', sa.Float(), nullable=True),
    sa.Column('OverallCapCompleted', sa.Float(), nullable=True),
    sa.Column('OverallValidated', sa.Float(), nullable=True),
    sa.Column('Accidentandincidentinvestigation', sa.Float(), nullable=True),
    sa.Column('Delegation', sa.Float(), nullable=True),
    sa.Column('Enforcement', sa.Float(), nullable=True),
    sa.Column('Exemptions', sa.Float(), nullable=True),
    sa.Column('Hazardidentificationandsafetyriskassessment', sa.Float(), nullable=True),
    sa.Column('Licensingcertificationauthorizationandapprovalobligations', sa.Float(), nullable=True),
    sa.Column('Managementofsafetyrisks', sa.Float(), nullable=True),
    sa.Column('Primaryaviationlegislation', sa.Float(), nullable=True),
    sa.Column('Qualifiedtechnicalpersonnel', sa.Float(), nullable=True),
    sa.Column('Resources', sa.Float(), nullable=True),
    sa.Column('Specificoperatingregulations', sa.Float(), nullable=True),
    sa.Column('StateAuthorities', sa.Float(), nullable=True),
    sa.Column('StateOrganizationalStructure', sa.Float(), nullable=True),
    sa.Column('Statefunctions', sa.Float(), nullable=True),
    sa.Column('Statesafetypromotion', sa.Float(), nullable=True),
    sa.Column('Surveillanceobligations', sa.Float(), nullable=True),
    sa.Column('Technicalguidancetoolsandprovisionofsafetycriticalinformation', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_ssp_foundation_State'), 'ssp_foundation', ['State'], unique=True, schema='icao')
    op.create_table('state_of_registries',
    sa.Column('RASG', sa.String(), nullable=True),
    sa.Column('iso_2_code', sa.String(length=2), nullable=True),
    sa.Column('iso_3_code', sa.String(length=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('UN_numerical_code', sa.String(), nullable=True),
    sa.Column('UN_region', sa.String(), nullable=True),
    sa.Column('UN_state_name', sa.String(), nullable=True),
    sa.Column('UN_state_name_html', sa.String(), nullable=True),
    sa.Column('ICAO_regional_office', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UN_numerical_code'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_state_of_registries_RASG'), 'state_of_registries', ['RASG'], unique=False, schema='icao')
    op.create_index(op.f('ix_icao_state_of_registries_iso_3_code'), 'state_of_registries', ['iso_3_code'], unique=False, schema='icao')
    op.create_table('state_safety_margins',
    sa.Column('State', sa.String(length=3), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('operations_ei', sa.Float(), nullable=True),
    sa.Column('support_ei', sa.Float(), nullable=True),
    sa.Column('airnavigation_ei', sa.Float(), nullable=True),
    sa.Column('departures', sa.Integer(), nullable=True),
    sa.Column('flagcarrier_flights', sa.Integer(), nullable=True),
    sa.Column('operations_margin', sa.Float(), nullable=True),
    sa.Column('support_margin', sa.Float(), nullable=True),
    sa.Column('airnavigation_margin', sa.Float(), nullable=True),
    sa.Column('operations_index', sa.Float(), nullable=True),
    sa.Column('support_index', sa.Float(), nullable=True),
    sa.Column('airnavigation_index', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_state_safety_margins_State'), 'state_safety_margins', ['State'], unique=True, schema='icao')
    op.create_table('state_traffic_statistics',
    sa.Column('State', sa.String(length=3), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Departures', sa.Integer(), nullable=True),
    sa.Column('Domestic', sa.Integer(), nullable=True),
    sa.Column('International', sa.Integer(), nullable=True),
    sa.Column('FlagCarrier_Flights', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('State', 'Year', name='uq_icao_state_traffic_statistics_State_Year'),
    schema='icao'
    )
    op.create_index(op.f('ix_icao_state_traffic_statistics_State'), 'state_traffic_statistics', ['State'], unique=False, schema='icao')
    op.alter_column('airlines', 'icao',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='api')
    op.alter_column('airlines', 'iata',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airlines', 'iata',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='api')
    op.alter_column('airlines', 'icao',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='api')
    op.drop_index(op.f('ix_icao_state_traffic_statistics_State'), table_name='state_traffic_statistics', schema='icao')
    op.drop_table('state_traffic_statistics', schema='icao')
    op.drop_index(op.f('ix_icao_state_safety_margins_State'), table_name='state_safety_margins', schema='icao')
    op.drop_table('state_safety_margins', schema='icao')
    op.drop_index(op.f('ix_icao_state_of_registries_iso_3_code'), table_name='state_of_registries', schema='icao')
    op.drop_index(op.f('ix_icao_state_of_registries_RASG'), table_name='state_of_registries', schema='icao')
    op.drop_table('state_of_registries', schema='icao')
    op.drop_index(op.f('ix_icao_ssp_foundation_State'), table_name='ssp_foundation', schema='icao')
    op.drop_table('ssp_foundation', schema='icao')
    op.drop_table('safety_related_occurrences', schema='icao')
    op.drop_table('passengersflow', schema='icao')
    op.drop_table('operators', schema='icao')
    op.drop_index(op.f('ix_icao_operator_statistics_State'), table_name='operator_statistics', schema='icao')
    op.drop_table('operator_statistics', schema='icao')
    op.drop_table('operator_risk_profiles', schema='icao')
    op.drop_table('operational_aerodrome_information', schema='icao')
    op.drop_table('metar_provider_location', schema='icao')
    op.drop_table('manufacturers', schema='icao')
    op.drop_table('location_indicators', schema='icao')
    op.drop_table('last_update', schema='icao')
    op.drop_table('international_airport_safety', schema='icao')
    op.drop_table('international_aerodromes', schema='icao')
    op.drop_table('incidents', schema='icao')
    op.drop_index(op.f('ix_icao_icao_member_states_iso_3_code'), table_name='icao_member_states', schema='icao')
    op.drop_index(op.f('ix_icao_icao_member_states_RASG'), table_name='icao_member_states', schema='icao')
    op.drop_table('icao_member_states', schema='icao')
    op.drop_table('finances', schema='icao')
    op.drop_table('countries_iso', schema='icao')
    op.drop_index(op.f('ix_icao_connections_State_A'), table_name='connections', schema='icao')
    op.drop_table('connections', schema='icao')
    op.drop_index(op.f('ix_icao_caahr_iso_3_code'), table_name='caahr', schema='icao')
    op.drop_index(op.f('ix_icao_caahr_iso_2_code'), table_name='caahr', schema='icao')
    op.drop_table('caahr', schema='icao')
    op.drop_index(op.f('ix_icao_asiap_prioritization_ro'), table_name='asiap_prioritization', schema='icao')
    op.drop_index(op.f('ix_icao_asiap_prioritization_iso_3_code'), table_name='asiap_prioritization', schema='icao')
    op.drop_table('asiap_prioritization', schema='icao')
    op.drop_table('airport_pbn_implementation', schema='icao')
    op.drop_table('aircraft_types', schema='icao')
    op.drop_index(op.f('ix_icao_aerodrome_statistics_State'), table_name='aerodrome_statistics', schema='icao')
    op.drop_table('aerodrome_statistics', schema='icao')
    op.drop_table('aerodrome_locations', schema='icao')
    op.drop_table('accidents', schema='icao')
    # ### end Alembic commands ###
