"""aixii baseline — create aviation schemas + shared enum types

Revision ID: aixii_baseline
Revises:
Create Date: 2026-06-27

Hand-written ROOT of the aixii migration tree. It provisions the per-domain schemas and the
shared ``airlabs.flight_status`` enum BEFORE the autogenerated table revision creates the
tables. Keeping schema/type creation here makes the aixii tree self-contained (it does not
silently depend on db-aixii-setup.sql having run first) and idempotent.

Next step: generate the table revision on top of this one::

    python tools/migrate.py revision aixii "initial aixii tables"   # autogenerate
    python tools/migrate.py upgrade  aixii head
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "aixii_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Aviation domains that own tables today. `api` now hosts the airlines reference list
# (api.airlines), so it is created here too. `icao` is still reserved for future use and is
# provisioned by db-aixii-setup.sql; no tables target it yet, so it is not created here.
# (CREATE SCHEMA IF NOT EXISTS is idempotent, so adding `api` is safe on already-provisioned DBs.)
SCHEMAS = ("cirium", "airlabs", "flightradar", "aviationedge", "api")


def upgrade() -> None:
    # imported lazily so module import (for revision discovery) never needs db-contract on path
    from Database.AirlabsModels import flight_status_type

    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')

    # shared native enum used by airlabs.flightsnapshots AND airlabs.aircraftstates; created
    # once here (the models declare it with create_type=False) so the table revision does not
    # emit two conflicting CREATE TYPE statements.
    flight_status_type.create(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    from Database.AirlabsModels import flight_status_type

    flight_status_type.drop(op.get_bind(), checkfirst=True)

    for schema in reversed(SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
