"""The insured-aircraft domain, rebuilt across four schemas

DROPS `insurance` WHOLE and replaces it with ref / fleet / leasing / policy, plus a single generic
change log in `audit`. Nothing is migrated because nothing was there: all eleven tables of the old
schema were empty, as were its two history tables.

WHY. The old schema held the airframe, the contract and the loss in one bag, and they are not one
subject. They have different lifetimes (an airframe outlives every contract written about it),
different sources (the lease comes from the lessor, the policy from the broker) and different read
patterns. The division that matters most is leasing vs policy - REQUIRED cover versus PROVIDED
cover - which is why `combined_single_limit`, `hull_spares_war_excess_liability` and
`hull_deductible_buy_down` exist on BOTH sides. That duplication is the feature. Full rationale and
the field-by-field mapping from the source specification: docs/insured-fleet.md.

WHAT ELSE GOES WITH IT. `insurance.insurance_claims` / `insurance_claim_history` and their routers
are removed - claims will be modelled again when the business gets to them. `forecast.acys_claims`
is a DIFFERENT thing (claims experience aggregated per airline and year, for the forecast model)
and is untouched.

HISTORY, in two kinds, both kept:
  * business history is the sequence of rows - a policy renewal is a new policy.policy and a new
    policy.coverage, the old ones keep their periods, so an aircraft insured for six years has six
    coverage rows;
  * technical history is audit.change_log - one row per INSERT/UPDATE/DELETE on every table here
    and on api.airlines, written by ONE trigger function instead of a `*_history` twin per table.

THIS DOWNGRADE IS ONE-WAY. It drops the new schemas and the api.airlines additions, but it does
NOT rebuild the old `insurance` domain: reversing a redesign of an empty schema would mean carrying
890 lines of superseded DDL that nobody would ever run. If it is truly needed, re-run the upgrades
of ad60f0b27298 -> fa38ae0ab542 -> insurance_schema_move by hand.

The raw SQL Alembic cannot autogenerate - the audit function and its triggers, the coverage
exclusion constraint, leasing.agreed_value_at() and the grants - lives in
`migration/insured_fleet_sql.py`, loaded by path because Alembic imports a revision as a standalone
module. Being invisible to autogenerate is also what stops a later `revision` proposing to drop it.

Revision ID: insured_fleet_rebuild
Revises: pbi_ground_snap
Create Date: 2026-09-21
"""
import importlib.util
import pathlib

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

_spec = importlib.util.spec_from_file_location(
    "_insured_fleet_sql", pathlib.Path(__file__).parents[1] / "insured_fleet_sql.py")
_sql = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_sql)

revision = "insured_fleet_rebuild"
down_revision = "pbi_ground_snap"
branch_labels = None
depends_on = None


_SCHEMA_COMMENTS = (
    ("ref", "Shared counterparty reference data: every legal entity the insured-aircraft domain "
            "names, whatever role it plays. The role is decided by the referencing column."),
    ("fleet", "The physical aircraft - airframe, type, installed engines. Outlives every lease and "
              "policy written about it. NOT the FlightRadar tracking fleet (cirium.asg_*)."),
    ("leasing", "Lease agreements and, per aircraft, the cover they REQUIRE. Twin of schema policy, "
                "which holds the cover PROVIDED - three limit columns exist on both sides on purpose."),
    ("policy", "Insurance policies and, per aircraft, the cover PROVIDED. Renewed yearly, so an "
               "aircraft accumulates one coverage row per policy period."),
    ("audit", "One change log for every table in ref/fleet/leasing/policy and api.airlines, written "
              "by audit.log_change()."),
)


def upgrade() -> None:
    # the coverage exclusion constraint needs it; already present, kept for a fresh cluster
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # --- out with the old. CASCADE takes the tables, the three enums, both audit functions and
    # their triggers; api.airlines is untouched (only the FKs pointing AT it, which live on the
    # dropped tables, go with them).
    op.execute("DROP SCHEMA IF EXISTS insurance CASCADE")

    for schema in _sql.SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # --- tables, indexes and the one new api.airlines column (autogenerated) -------------------
    op.create_table('party',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), sa.Computed('upper(btrim(name))', persisted=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized', name='uq_party_name_normalized'),
    schema='ref'
    )
    op.create_table('party_contact',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['ref.party.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ref'
    )
    op.create_index('ix_party_contact_email', 'party_contact', ['email'], unique=False, schema='ref')
    op.create_index(op.f('ix_ref_party_contact_party_id'), 'party_contact', ['party_id'], unique=False, schema='ref')
    op.create_table('aircraft_type',
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('master_series', sa.String(), nullable=False),
    sa.Column('master_series_normalized', sa.String(), sa.Computed('upper(btrim(master_series))', persisted=True), nullable=False),
    sa.Column('template_url', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_series_normalized', name='uq_aircraft_type_master_series'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_aircraft_type_manufacturer'), 'aircraft_type', ['manufacturer'], unique=False, schema='fleet')
    op.create_table('aircraft',
    sa.Column('registration', sa.String(), nullable=False),
    sa.Column('registration_normalized', sa.String(), sa.Computed("upper(regexp_replace(registration, '[^A-Za-z0-9]', '', 'g'))", persisted=True), nullable=False),
    sa.Column('msn', sa.String(), nullable=True),
    sa.Column('aircraft_type_id', sa.BigInteger(), nullable=True),
    sa.Column('airline_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['fleet.aircraft_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['airline_id'], ['api.airlines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index('ix_aircraft_registration_normalized', 'aircraft', ['registration_normalized'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_aircraft_aircraft_type_id'), 'aircraft', ['aircraft_type_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_aircraft_airline_id'), 'aircraft', ['airline_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_aircraft_msn'), 'aircraft', ['msn'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_aircraft_registration'), 'aircraft', ['registration'], unique=False, schema='fleet')
    op.create_index('uq_aircraft_msn', 'aircraft', ['msn'], unique=True, schema='fleet', postgresql_where=sa.text('msn IS NOT NULL'))
    op.create_table('aircraft_engine',
    sa.Column('aircraft_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('master_series', sa.String(), nullable=True),
    sa.Column('msn', sa.String(), nullable=True),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 4', name='ck_aircraft_engine_position'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['fleet.aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aircraft_id', 'position', 'installed_on', name='uq_aircraft_engine_installation', postgresql_nulls_not_distinct=True),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_aircraft_engine_aircraft_id'), 'aircraft_engine', ['aircraft_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_aircraft_engine_msn'), 'aircraft_engine', ['msn'], unique=False, schema='fleet')
    op.create_table('agreement',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), sa.Computed('upper(btrim(name))', persisted=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('lessor_id', sa.BigInteger(), nullable=True),
    sa.Column('alternative_contract_party', sa.Text(), nullable=True),
    sa.Column('other_contracts', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR', 'GBP')", name='ck_agreement_currency'),
    sa.CheckConstraint('currency = upper(currency)', name='ck_agreement_currency_upper'),
    sa.ForeignKeyConstraint(['lessor_id'], ['ref.party.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized', 'start_date', name='uq_agreement_name_start', postgresql_nulls_not_distinct=True),
    schema='leasing'
    )
    op.create_index(op.f('ix_leasing_agreement_lessor_id'), 'agreement', ['lessor_id'], unique=False, schema='leasing')
    op.create_table('aircraft_lease',
    sa.Column('aircraft_id', sa.BigInteger(), nullable=False),
    sa.Column('agreement_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('agreed_value_preliminary', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('agreed_value_final', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('agreed_value_fixed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('depreciation_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('depreciation_start_date', sa.Date(), nullable=True),
    sa.Column('combined_single_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_spares_war_excess_liability', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_deductible_buy_down', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source', sa.Enum('manual', 'lease_agreement', 'cirium', name='lease_source', schema='leasing'), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LEAST(agreed_value_preliminary, agreed_value_final, combined_single_limit, hull_spares_war_excess_liability, hull_deductible_buy_down) >= 0', name='ck_aircraft_lease_amounts_non_negative'),
    sa.CheckConstraint('depreciation_ratio IS NULL OR depreciation_ratio BETWEEN 0 AND 100', name='ck_aircraft_lease_depreciation_ratio'),
    sa.ForeignKeyConstraint(['agreement_id'], ['leasing.agreement.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['fleet.aircraft.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aircraft_id', 'agreement_id', 'effective_date', name='uq_aircraft_lease_effective'),
    schema='leasing'
    )
    op.create_index('ix_aircraft_lease_aircraft_effective', 'aircraft_lease', ['aircraft_id', 'effective_date'], unique=False, schema='leasing')
    op.create_index(op.f('ix_leasing_aircraft_lease_agreement_id'), 'aircraft_lease', ['agreement_id'], unique=False, schema='leasing')
    op.create_index(op.f('ix_leasing_aircraft_lease_aircraft_id'), 'aircraft_lease', ['aircraft_id'], unique=False, schema='leasing')
    op.create_table('policy',
    sa.Column('insured_id', sa.BigInteger(), nullable=False),
    sa.Column('reinsured_id', sa.BigInteger(), nullable=True),
    sa.Column('retrocedent_id', sa.BigInteger(), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('hull_all_risks_deductible', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('spares_deductible', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_deductible_buy_down', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_deductible_aggregate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('combined_single_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_war_overall_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_spares_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_spares_war_excess_liability', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_war_confiscation_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hull_war_confiscation_limit_selected_country', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('selected_country', sa.String(), nullable=True),
    sa.Column('reinsured_amount', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('cut_through_clause', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('USD', 'EUR', 'GBP')", name='ck_policy_currency'),
    sa.CheckConstraint('LEAST(hull_all_risks_deductible, spares_deductible, hull_deductible_buy_down, hull_deductible_aggregate, combined_single_limit, hull_war_overall_limit, hull_spares_limit, hull_spares_war_excess_liability, hull_war_confiscation_limit, hull_war_confiscation_limit_selected_country) >= 0', name='ck_policy_amounts_non_negative'),
    sa.CheckConstraint('currency = upper(currency)', name='ck_policy_currency_upper'),
    sa.CheckConstraint('period_to IS NULL OR period_to >= period_from', name='ck_policy_period'),
    sa.CheckConstraint('reinsured_amount IS NULL OR reinsured_amount BETWEEN 0 AND 100', name='ck_policy_reinsured_amount'),
    sa.ForeignKeyConstraint(['insured_id'], ['ref.party.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reinsured_id'], ['ref.party.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retrocedent_id'], ['ref.party.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insured_id', 'period_from', 'period_to', name='uq_policy_insured_period', postgresql_nulls_not_distinct=True),
    schema='policy'
    )
    op.create_index('ix_policy_period', 'policy', ['period_from', 'period_to'], unique=False, schema='policy')
    op.create_index(op.f('ix_policy_policy_insured_id'), 'policy', ['insured_id'], unique=False, schema='policy')
    op.create_index(op.f('ix_policy_policy_reinsured_id'), 'policy', ['reinsured_id'], unique=False, schema='policy')
    op.create_index(op.f('ix_policy_policy_retrocedent_id'), 'policy', ['retrocedent_id'], unique=False, schema='policy')
    op.create_table('coverage',
    sa.Column('aircraft_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.Column('covered_from', sa.Date(), nullable=False),
    sa.Column('covered_to', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('covered_to IS NULL OR covered_to >= covered_from', name='ck_coverage_period'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['fleet.aircraft.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.policy.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aircraft_id', 'policy_id', 'covered_from', name='uq_coverage_aircraft_policy'),
    schema='policy'
    )
    op.create_index('ix_coverage_period', 'coverage', ['covered_from', 'covered_to'], unique=False, schema='policy')
    op.create_index(op.f('ix_policy_coverage_aircraft_id'), 'coverage', ['aircraft_id'], unique=False, schema='policy')
    op.create_index(op.f('ix_policy_coverage_policy_id'), 'coverage', ['policy_id'], unique=False, schema='policy')
    op.create_table('change_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('row_id', sa.BigInteger(), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('old_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index('ix_change_log_changed_at', 'change_log', ['changed_at'], unique=False, schema='audit')
    op.create_index('ix_change_log_changed_by', 'change_log', ['changed_by'], unique=False, schema='audit')
    op.create_index('ix_change_log_subject', 'change_log', ['schema_name', 'table_name', 'row_id', 'changed_at'], unique=False, schema='audit', postgresql_using='btree')
    op.add_column('airlines', sa.Column('logo_url', sa.Text(), nullable=True), schema='api')

    # --- an aircraft is covered by at most one policy on any given day -------------------------
    op.execute(_sql.COVERAGE_EXCLUSION)
    op.execute(_sql.COVERAGE_EXCLUSION_COMMENT)

    # --- the change log ------------------------------------------------------------------------
    op.execute(_sql.AUDIT_FUNCTION)
    op.execute(_sql.AUDIT_FUNCTION_COMMENT)
    for schema, table in _sql.AUDITED:
        op.execute(_sql.audit_trigger(schema, table))

    # --- the agreed-value calculation -----------------------------------------------------------
    op.execute(_sql.AGREED_VALUE_FUNCTION)
    op.execute(_sql.AGREED_VALUE_COMMENT)

    # --- grants, mirroring what the dropped `insurance` schema had ------------------------------
    for schema in _sql.DATA_SCHEMAS:
        for statement in _sql.grants(schema):
            op.execute(statement)
    for statement in _sql.AUDIT_GRANTS:
        op.execute(statement)

    # --- what each schema is for, readable from psql --------------------------------------------
    for schema, comment in _SCHEMA_COMMENTS:
        op.execute(f"COMMENT ON SCHEMA {schema} IS '{comment}'")
    op.execute(
        "COMMENT ON COLUMN api.airlines.logo_url IS "
        "'URL into the platform image store. Never the bytes - a grid reads every airline on the "
        "page and a blob per row would drag megabytes through the connection.'"
    )


def downgrade() -> None:
    """One-way, deliberately — see the module docstring. The new domain goes; the old one is NOT
    rebuilt, so the database after this is NOT what revision `pbi_ground_snap` describes."""
    # api.airlines outlives the schema drops, so its trigger and column have to go explicitly
    op.execute(_sql.drop_audit_trigger("api", "airlines"))
    op.drop_column("airlines", "logo_url", schema="api")
    # CASCADE takes the tables, the lease_source enum, both functions and the remaining triggers
    for schema in reversed(_sql.SCHEMAS):
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
