"""ref.country: the world's countries, for the country picker

Every country and territory of ISO 3166-1 (249) plus Kosovo (XK / XKX, the user-assigned code
aviation uses). `name` is the ISO 3166-1 English short name, which is the FULL form the contracts
use ('Russian Federation', 'United Kingdom of Great Britain and Northern Ireland', 'Iran (Islamic
Republic of)'); `common_name` is the everyday form where it differs ('Russia'), so a search for
either finds it. Read-only reference data: the rows are written here and nowhere else; the API
serves them at GET /ref/countries.

Revision ID: ref_country
Revises: policy_parties_mtow
Create Date: 2026-09-28
"""
from alembic import op
from sqlalchemy import text

revision = "ref_country"
down_revision = "policy_parties_mtow"
branch_labels = None
depends_on = None

_READ_ROLES = "grp_aixii_read, grp_aviation_write, svc_external_worker"
_WRITE_ROLE = "grp_api_write"

# (ISO alpha-2, ISO alpha-3, ISO 3166-1 English short name, everyday name when different)
COUNTRIES = [
    ("AF", "AFG", "Afghanistan", None),
    ("AX", "ALA", "Åland Islands", "Aland Islands"),
    ("AL", "ALB", "Albania", None),
    ("DZ", "DZA", "Algeria", None),
    ("AS", "ASM", "American Samoa", None),
    ("AD", "AND", "Andorra", None),
    ("AO", "AGO", "Angola", None),
    ("AI", "AIA", "Anguilla", None),
    ("AQ", "ATA", "Antarctica", None),
    ("AG", "ATG", "Antigua and Barbuda", None),
    ("AR", "ARG", "Argentina", None),
    ("AM", "ARM", "Armenia", None),
    ("AW", "ABW", "Aruba", None),
    ("AU", "AUS", "Australia", None),
    ("AT", "AUT", "Austria", None),
    ("AZ", "AZE", "Azerbaijan", None),
    ("BS", "BHS", "Bahamas", None),
    ("BH", "BHR", "Bahrain", None),
    ("BD", "BGD", "Bangladesh", None),
    ("BB", "BRB", "Barbados", None),
    ("BY", "BLR", "Belarus", None),
    ("BE", "BEL", "Belgium", None),
    ("BZ", "BLZ", "Belize", None),
    ("BJ", "BEN", "Benin", None),
    ("BM", "BMU", "Bermuda", None),
    ("BT", "BTN", "Bhutan", None),
    ("BO", "BOL", "Bolivia (Plurinational State of)", "Bolivia"),
    ("BQ", "BES", "Bonaire, Sint Eustatius and Saba", "Caribbean Netherlands"),
    ("BA", "BIH", "Bosnia and Herzegovina", None),
    ("BW", "BWA", "Botswana", None),
    ("BV", "BVT", "Bouvet Island", None),
    ("BR", "BRA", "Brazil", None),
    ("IO", "IOT", "British Indian Ocean Territory", None),
    ("BN", "BRN", "Brunei Darussalam", "Brunei"),
    ("BG", "BGR", "Bulgaria", None),
    ("BF", "BFA", "Burkina Faso", None),
    ("BI", "BDI", "Burundi", None),
    ("CV", "CPV", "Cabo Verde", "Cape Verde"),
    ("KH", "KHM", "Cambodia", None),
    ("CM", "CMR", "Cameroon", None),
    ("CA", "CAN", "Canada", None),
    ("KY", "CYM", "Cayman Islands", None),
    ("CF", "CAF", "Central African Republic", None),
    ("TD", "TCD", "Chad", None),
    ("CL", "CHL", "Chile", None),
    ("CN", "CHN", "China", None),
    ("CX", "CXR", "Christmas Island", None),
    ("CC", "CCK", "Cocos (Keeling) Islands", "Cocos Islands"),
    ("CO", "COL", "Colombia", None),
    ("KM", "COM", "Comoros", None),
    ("CG", "COG", "Congo", "Republic of the Congo"),
    ("CD", "COD", "Congo (Democratic Republic of the)", "DR Congo"),
    ("CK", "COK", "Cook Islands", None),
    ("CR", "CRI", "Costa Rica", None),
    ("CI", "CIV", "Côte d'Ivoire", "Ivory Coast"),
    ("HR", "HRV", "Croatia", None),
    ("CU", "CUB", "Cuba", None),
    ("CW", "CUW", "Curaçao", "Curacao"),
    ("CY", "CYP", "Cyprus", None),
    ("CZ", "CZE", "Czechia", "Czech Republic"),
    ("DK", "DNK", "Denmark", None),
    ("DJ", "DJI", "Djibouti", None),
    ("DM", "DMA", "Dominica", None),
    ("DO", "DOM", "Dominican Republic", None),
    ("EC", "ECU", "Ecuador", None),
    ("EG", "EGY", "Egypt", None),
    ("SV", "SLV", "El Salvador", None),
    ("GQ", "GNQ", "Equatorial Guinea", None),
    ("ER", "ERI", "Eritrea", None),
    ("EE", "EST", "Estonia", None),
    ("SZ", "SWZ", "Eswatini", "Swaziland"),
    ("ET", "ETH", "Ethiopia", None),
    ("FK", "FLK", "Falkland Islands (Malvinas)", "Falkland Islands"),
    ("FO", "FRO", "Faroe Islands", None),
    ("FJ", "FJI", "Fiji", None),
    ("FI", "FIN", "Finland", None),
    ("FR", "FRA", "France", None),
    ("GF", "GUF", "French Guiana", None),
    ("PF", "PYF", "French Polynesia", None),
    ("TF", "ATF", "French Southern Territories", None),
    ("GA", "GAB", "Gabon", None),
    ("GM", "GMB", "Gambia", None),
    ("GE", "GEO", "Georgia", None),
    ("DE", "DEU", "Germany", None),
    ("GH", "GHA", "Ghana", None),
    ("GI", "GIB", "Gibraltar", None),
    ("GR", "GRC", "Greece", None),
    ("GL", "GRL", "Greenland", None),
    ("GD", "GRD", "Grenada", None),
    ("GP", "GLP", "Guadeloupe", None),
    ("GU", "GUM", "Guam", None),
    ("GT", "GTM", "Guatemala", None),
    ("GG", "GGY", "Guernsey", None),
    ("GN", "GIN", "Guinea", None),
    ("GW", "GNB", "Guinea-Bissau", None),
    ("GY", "GUY", "Guyana", None),
    ("HT", "HTI", "Haiti", None),
    ("HM", "HMD", "Heard Island and McDonald Islands", None),
    ("VA", "VAT", "Holy See", "Vatican City"),
    ("HN", "HND", "Honduras", None),
    ("HK", "HKG", "Hong Kong", None),
    ("HU", "HUN", "Hungary", None),
    ("IS", "ISL", "Iceland", None),
    ("IN", "IND", "India", None),
    ("ID", "IDN", "Indonesia", None),
    ("IR", "IRN", "Iran (Islamic Republic of)", "Iran"),
    ("IQ", "IRQ", "Iraq", None),
    ("IE", "IRL", "Ireland", None),
    ("IM", "IMN", "Isle of Man", None),
    ("IL", "ISR", "Israel", None),
    ("IT", "ITA", "Italy", None),
    ("JM", "JAM", "Jamaica", None),
    ("JP", "JPN", "Japan", None),
    ("JE", "JEY", "Jersey", None),
    ("JO", "JOR", "Jordan", None),
    ("KZ", "KAZ", "Kazakhstan", None),
    ("KE", "KEN", "Kenya", None),
    ("KI", "KIR", "Kiribati", None),
    ("KP", "PRK", "Korea (Democratic People's Republic of)", "North Korea"),
    ("KR", "KOR", "Korea (Republic of)", "South Korea"),
    ("XK", "XKX", "Kosovo", None),
    ("KW", "KWT", "Kuwait", None),
    ("KG", "KGZ", "Kyrgyzstan", None),
    ("LA", "LAO", "Lao People's Democratic Republic", "Laos"),
    ("LV", "LVA", "Latvia", None),
    ("LB", "LBN", "Lebanon", None),
    ("LS", "LSO", "Lesotho", None),
    ("LR", "LBR", "Liberia", None),
    ("LY", "LBY", "Libya", None),
    ("LI", "LIE", "Liechtenstein", None),
    ("LT", "LTU", "Lithuania", None),
    ("LU", "LUX", "Luxembourg", None),
    ("MO", "MAC", "Macao", "Macau"),
    ("MG", "MDG", "Madagascar", None),
    ("MW", "MWI", "Malawi", None),
    ("MY", "MYS", "Malaysia", None),
    ("MV", "MDV", "Maldives", None),
    ("ML", "MLI", "Mali", None),
    ("MT", "MLT", "Malta", None),
    ("MH", "MHL", "Marshall Islands", None),
    ("MQ", "MTQ", "Martinique", None),
    ("MR", "MRT", "Mauritania", None),
    ("MU", "MUS", "Mauritius", None),
    ("YT", "MYT", "Mayotte", None),
    ("MX", "MEX", "Mexico", None),
    ("FM", "FSM", "Micronesia (Federated States of)", "Micronesia"),
    ("MD", "MDA", "Moldova (Republic of)", "Moldova"),
    ("MC", "MCO", "Monaco", None),
    ("MN", "MNG", "Mongolia", None),
    ("ME", "MNE", "Montenegro", None),
    ("MS", "MSR", "Montserrat", None),
    ("MA", "MAR", "Morocco", None),
    ("MZ", "MOZ", "Mozambique", None),
    ("MM", "MMR", "Myanmar", "Burma"),
    ("NA", "NAM", "Namibia", None),
    ("NR", "NRU", "Nauru", None),
    ("NP", "NPL", "Nepal", None),
    ("NL", "NLD", "Netherlands (Kingdom of the)", "Netherlands"),
    ("NC", "NCL", "New Caledonia", None),
    ("NZ", "NZL", "New Zealand", None),
    ("NI", "NIC", "Nicaragua", None),
    ("NE", "NER", "Niger", None),
    ("NG", "NGA", "Nigeria", None),
    ("NU", "NIU", "Niue", None),
    ("NF", "NFK", "Norfolk Island", None),
    ("MK", "MKD", "North Macedonia", "Macedonia"),
    ("MP", "MNP", "Northern Mariana Islands", None),
    ("NO", "NOR", "Norway", None),
    ("OM", "OMN", "Oman", None),
    ("PK", "PAK", "Pakistan", None),
    ("PW", "PLW", "Palau", None),
    ("PS", "PSE", "Palestine, State of", "Palestine"),
    ("PA", "PAN", "Panama", None),
    ("PG", "PNG", "Papua New Guinea", None),
    ("PY", "PRY", "Paraguay", None),
    ("PE", "PER", "Peru", None),
    ("PH", "PHL", "Philippines", None),
    ("PN", "PCN", "Pitcairn", "Pitcairn Islands"),
    ("PL", "POL", "Poland", None),
    ("PT", "PRT", "Portugal", None),
    ("PR", "PRI", "Puerto Rico", None),
    ("QA", "QAT", "Qatar", None),
    ("RE", "REU", "Réunion", "Reunion"),
    ("RO", "ROU", "Romania", None),
    ("RU", "RUS", "Russian Federation", "Russia"),
    ("RW", "RWA", "Rwanda", None),
    ("BL", "BLM", "Saint Barthélemy", "Saint Barthelemy"),
    ("SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "Saint Helena"),
    ("KN", "KNA", "Saint Kitts and Nevis", None),
    ("LC", "LCA", "Saint Lucia", None),
    ("MF", "MAF", "Saint Martin (French part)", "Saint Martin"),
    ("PM", "SPM", "Saint Pierre and Miquelon", None),
    ("VC", "VCT", "Saint Vincent and the Grenadines", None),
    ("WS", "WSM", "Samoa", None),
    ("SM", "SMR", "San Marino", None),
    ("ST", "STP", "Sao Tome and Principe", None),
    ("SA", "SAU", "Saudi Arabia", None),
    ("SN", "SEN", "Senegal", None),
    ("RS", "SRB", "Serbia", None),
    ("SC", "SYC", "Seychelles", None),
    ("SL", "SLE", "Sierra Leone", None),
    ("SG", "SGP", "Singapore", None),
    ("SX", "SXM", "Sint Maarten (Dutch part)", "Sint Maarten"),
    ("SK", "SVK", "Slovakia", None),
    ("SI", "SVN", "Slovenia", None),
    ("SB", "SLB", "Solomon Islands", None),
    ("SO", "SOM", "Somalia", None),
    ("ZA", "ZAF", "South Africa", None),
    ("GS", "SGS", "South Georgia and the South Sandwich Islands", None),
    ("SS", "SSD", "South Sudan", None),
    ("ES", "ESP", "Spain", None),
    ("LK", "LKA", "Sri Lanka", None),
    ("SD", "SDN", "Sudan", None),
    ("SR", "SUR", "Suriname", None),
    ("SJ", "SJM", "Svalbard and Jan Mayen", None),
    ("SE", "SWE", "Sweden", None),
    ("CH", "CHE", "Switzerland", None),
    ("SY", "SYR", "Syrian Arab Republic", "Syria"),
    ("TW", "TWN", "Taiwan, Province of China", "Taiwan"),
    ("TJ", "TJK", "Tajikistan", None),
    ("TZ", "TZA", "Tanzania, United Republic of", "Tanzania"),
    ("TH", "THA", "Thailand", None),
    ("TL", "TLS", "Timor-Leste", "East Timor"),
    ("TG", "TGO", "Togo", None),
    ("TK", "TKL", "Tokelau", None),
    ("TO", "TON", "Tonga", None),
    ("TT", "TTO", "Trinidad and Tobago", None),
    ("TN", "TUN", "Tunisia", None),
    ("TR", "TUR", "Türkiye", "Turkey"),
    ("TM", "TKM", "Turkmenistan", None),
    ("TC", "TCA", "Turks and Caicos Islands", None),
    ("TV", "TUV", "Tuvalu", None),
    ("UG", "UGA", "Uganda", None),
    ("UA", "UKR", "Ukraine", None),
    ("AE", "ARE", "United Arab Emirates", "UAE"),
    ("GB", "GBR", "United Kingdom of Great Britain and Northern Ireland", "United Kingdom"),
    ("US", "USA", "United States of America", "United States"),
    ("UM", "UMI", "United States Minor Outlying Islands", None),
    ("UY", "URY", "Uruguay", None),
    ("UZ", "UZB", "Uzbekistan", None),
    ("VU", "VUT", "Vanuatu", None),
    ("VE", "VEN", "Venezuela (Bolivarian Republic of)", "Venezuela"),
    ("VN", "VNM", "Viet Nam", "Vietnam"),
    ("VG", "VGB", "Virgin Islands (British)", "British Virgin Islands"),
    ("VI", "VIR", "Virgin Islands (U.S.)", "US Virgin Islands"),
    ("WF", "WLF", "Wallis and Futuna", None),
    ("EH", "ESH", "Western Sahara", None),
    ("YE", "YEM", "Yemen", None),
    ("ZM", "ZMB", "Zambia", None),
    ("ZW", "ZWE", "Zimbabwe", None),
]


def upgrade() -> None:
    assert len(COUNTRIES) == 250, len(COUNTRIES)
    for i in (0, 1, 2):
        assert len({c[i] for c in COUNTRIES}) == len(COUNTRIES), f"duplicate in column {i}"

    op.execute("""
        CREATE TABLE ref.country (
            id          bigserial PRIMARY KEY,
            iso2        varchar(2) NOT NULL,
            iso3        varchar(3) NOT NULL,
            name        varchar NOT NULL,
            common_name varchar,
            created_at  timestamp NOT NULL DEFAULT now(),
            updated_at  timestamp NOT NULL DEFAULT now(),
            CONSTRAINT uq_country_iso2 UNIQUE (iso2),
            CONSTRAINT uq_country_iso3 UNIQUE (iso3),
            CONSTRAINT uq_country_name UNIQUE (name),
            CONSTRAINT ck_country_iso2 CHECK (iso2 = upper(iso2) AND length(iso2) = 2),
            CONSTRAINT ck_country_iso3 CHECK (iso3 = upper(iso3) AND length(iso3) = 3)
        )
    """)
    op.execute("COMMENT ON TABLE ref.country IS 'ISO 3166-1 countries and territories (+ Kosovo, "
               "XK). name = the ISO English short name, i.e. the full form; common_name = the "
               "everyday form for search.'")
    bind = op.get_bind()
    bind.execute(
        text("INSERT INTO ref.country (iso2, iso3, name, common_name) "
             "VALUES (:iso2, :iso3, :name, :common_name)"),
        [{"iso2": a, "iso3": b, "name": n, "common_name": c} for a, b, n, c in COUNTRIES])
    op.execute(f"GRANT SELECT ON ref.country TO {_READ_ROLES}, {_WRITE_ROLE}")


def downgrade() -> None:
    op.execute("DROP TABLE ref.country")
