"""fix index

Revision ID: 9ac862e4b6ac
Revises: 
Create Date: 2026-05-13 15:34:26.254513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac862e4b6ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cirium_revision_serial', 'ciriumaircraft', ['revision_id', 'Serial Number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cirium_revision_serial', table_name='ciriumaircraft')
    # ### end Alembic commands ###
