"""add plan_type column

Revision ID: b195d3a861a5
Revises: 9ac862e4b6ac
Create Date: 2026-06-18 17:35:40.106641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b195d3a861a5'
down_revision: Union[str, Sequence[str], None] = '9ac862e4b6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asgaircraft', sa.Column('plan_type', sa.String(), nullable=True))
    op.add_column('ciriumaircraft', sa.Column('plan_type', sa.String(), nullable=True))
    op.add_column('ciriumaircraftsdelta', sa.Column('plan_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ciriumaircraftsdelta', 'plan_type')
    op.drop_column('ciriumaircraft', 'plan_type')
    op.drop_column('asgaircraft', 'plan_type')
    # ### end Alembic commands ###
