"""Edit registration table

Revision ID: 0dbffc5657c0
Revises: 42fc13f5920f
Create Date: 2026-01-07 17:01:29.384600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbffc5657c0'
down_revision: Union[str, Sequence[str], None] = '42fc13f5920f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('reg', sa.String(), nullable=False),
    sa.Column('msn', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('indashboard', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msn')
    )
    op.create_index(op.f('ix_registration_reg'), 'registration', ['reg'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_reg'), table_name='registration')
    op.drop_table('registration')
    # ### end Alembic commands ###
