"""Edit registration table

Revision ID: 42fc13f5920f
Revises: b2bded37b33e
Create Date: 2026-01-07 16:52:38.265309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fc13f5920f'
down_revision: Union[str, Sequence[str], None] = 'b2bded37b33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lease_outputs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('registration', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('registration', 'msn',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('registration', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('registration_reg_key'), 'registration', type_='unique')
    op.create_index(op.f('ix_registration_reg'), 'registration', ['reg'], unique=False)
    op.create_unique_constraint(None, 'registration', ['msn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registration', type_='unique')
    op.drop_index(op.f('ix_registration_reg'), table_name='registration')
    op.create_unique_constraint(op.f('registration_reg_key'), 'registration', ['reg'], postgresql_nulls_not_distinct=False)
    op.alter_column('registration', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('registration', 'msn',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('registration', 'status')
    op.alter_column('lease_outputs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('guest', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
