"""test2

Revision ID: 79e73a7b692d
Revises: a9e8ab103854
Create Date: 2026-01-26 20:12:32.569185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e73a7b692d'
down_revision: Union[str, Sequence[str], None] = 'a9e8ab103854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airline', 'icao_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline', sa.Column('icao_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
