"""add airlines table

Revision ID: 88335a495410
Revises: 0dbffc5657c0
Create Date: 2026-01-13 00:24:24.024176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88335a495410'
down_revision: Union[str, Sequence[str], None] = '0dbffc5657c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('airline_name', sa.String(), nullable=False),
    sa.Column('icao', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airline_airline_name'), 'airline', ['airline_name'], unique=False)
    op.create_index(op.f('ix_airline_icao'), 'airline', ['icao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airline_icao'), table_name='airline')
    op.drop_index(op.f('ix_airline_airline_name'), table_name='airline')
    op.drop_table('airline')
    # ### end Alembic commands ###
