"""test

Revision ID: a9e8ab103854
Revises: d7c8570c8c13
Create Date: 2026-01-26 20:06:31.516152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e8ab103854'
down_revision: Union[str, Sequence[str], None] = 'd7c8570c8c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline', sa.Column('icao_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airline', 'icao_2')
    # ### end Alembic commands ###
