"""add lease table

Revision ID: b2bded37b33e
Revises: 
Create Date: 2025-11-21 13:29:14.825168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2bded37b33e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lease_outputs',
    sa.Column('File name', sa.String(), nullable=False),
    sa.Column('Aircraft Count', sa.Integer(), nullable=False),
    sa.Column('Engines Count', sa.Integer(), nullable=False),
    sa.Column('Aircraft Type', sa.String(), nullable=True),
    sa.Column('MSN', sa.String(), nullable=True),
    sa.Column('Engines Manufacture', sa.String(), nullable=True),
    sa.Column('Engines Models', sa.String(), nullable=True),
    sa.Column('Engine1 MSN', sa.String(), nullable=True),
    sa.Column('Engine2 MSN', sa.String(), nullable=True),
    sa.Column('Aircraft Registration', sa.String(), nullable=True),
    sa.Column('Agreement dated as of', sa.String(), nullable=True),
    sa.Column('Lessee', sa.String(), nullable=True),
    sa.Column('Lessor', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('Damage Proceeds Threshold', sa.String(), nullable=True),
    sa.Column('Aircraft Agreed Value', sa.String(), nullable=True),
    sa.Column('Hull All Risks', sa.String(), nullable=True),
    sa.Column('Minimal Liability Coverages', sa.String(), nullable=True),
    sa.Column('All Risks Deductible', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_outputs_File name'), 'lease_outputs', ['File name'], unique=True)
    op.create_table('registration',
    sa.Column('reg', sa.String(), nullable=False),
    sa.Column('msn', sa.Integer(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('indashboard', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    op.drop_index(op.f('ix_lease_outputs_File name'), table_name='lease_outputs')
    op.drop_table('lease_outputs')
    # ### end Alembic commands ###
