from .HealthCheck import router as health
from .Root import router as root
from .StatusCheck import router as status
from .Files import router as files
from .Webhook import router as webhook
from .Database import router as database
from .FlightRadar import router as flight_radar
from .Scheduler import router as scheduler
from .QueueAdmin import router as queues
from .Tokens import router as tokens
from .PredictiveUtilisation import router as predictive_utilisation
