"""fix nullable

Revision ID: 32bd7407cf45
Revises: e6dab0a7543c
Create Date: 2026-01-07 19:35:57.580209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bd7407cf45'
down_revision: Union[str, Sequence[str], None] = 'e6dab0a7543c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flightsnapshots', 'airline_icao',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('flightsnapshots', 'airline_iata',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('flightsnapshots', 'aircraft_icao',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('flightsnapshots', 'flight_icao',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('flightsnapshots', 'flight_iata',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('flightsnapshots', 'flight_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('flightsnapshots', 'dep_icao',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('flightsnapshots', 'dep_iata',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('flightsnapshots', 'arr_icao',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('flightsnapshots', 'arr_iata',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('flightsnapshots', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('flightsnapshots', 'lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('flightsnapshots', 'alt',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('flightsnapshots', 'dir',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('flightsnapshots', 'speed',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('flightsnapshots', 'v_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('flightsnapshots', 'squawk',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('flightsnapshots', 'flag',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flightsnapshots', 'flag',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('flightsnapshots', 'squawk',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('flightsnapshots', 'v_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('flightsnapshots', 'speed',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('flightsnapshots', 'dir',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.alter_column('flightsnapshots', 'alt',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('flightsnapshots', 'lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('flightsnapshots', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('flightsnapshots', 'arr_iata',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('flightsnapshots', 'arr_icao',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('flightsnapshots', 'dep_iata',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('flightsnapshots', 'dep_icao',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('flightsnapshots', 'flight_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('flightsnapshots', 'flight_iata',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('flightsnapshots', 'flight_icao',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('flightsnapshots', 'aircraft_icao',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('flightsnapshots', 'airline_iata',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('flightsnapshots', 'airline_icao',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###
