"""initial

Revision ID: 3db7e758dd0a
Revises: aa6b1bc8e220
Create Date: 2026-01-06 12:50:46.145589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db7e758dd0a'
down_revision: Union[str, Sequence[str], None] = 'aa6b1bc8e220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flightsnapshots',
    sa.Column('hex', sa.String(length=6), nullable=False),
    sa.Column('reg_number', sa.String(length=16), nullable=False),
    sa.Column('airline_icao', sa.String(length=3), nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=False),
    sa.Column('aircraft_icao', sa.String(length=4), nullable=False),
    sa.Column('flight_icao', sa.String(length=10), nullable=False),
    sa.Column('flight_iata', sa.String(length=10), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('dep_icao', sa.String(length=4), nullable=False),
    sa.Column('dep_iata', sa.String(length=3), nullable=False),
    sa.Column('arr_icao', sa.String(length=4), nullable=False),
    sa.Column('arr_iata', sa.String(length=3), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('alt', sa.Integer(), nullable=False),
    sa.Column('dir', sa.SmallInteger(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('v_speed', sa.Integer(), nullable=False),
    sa.Column('squawk', sa.String(length=4), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'EN_ROUTE', 'LANDED', name='flight_status'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_airline_iata', 'flightsnapshots', ['airline_iata'], unique=False)
    op.create_index('ix_snapshots_airline_icao', 'flightsnapshots', ['airline_icao'], unique=False)
    op.create_index('ix_snapshots_reg_number', 'flightsnapshots', ['reg_number'], unique=False)
    op.create_index('ix_snapshots_reg_status', 'flightsnapshots', ['reg_number', 'status'], unique=False)
    op.create_index('ix_snapshots_reg_updated', 'flightsnapshots', ['reg_number', sa.literal_column('updated DESC')], unique=False)
    op.create_index('ix_snapshots_updated', 'flightsnapshots', ['updated'], unique=False)
    op.create_table('aircraftstates',
    sa.Column('reg_number', sa.String(length=16), nullable=False),
    sa.Column('airline_icao', sa.String(length=3), nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'EN_ROUTE', 'LANDED', name='flight_status'), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['flightsnapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('reg_number', 'id')
    )
    op.create_index(op.f('ix_aircraftstates_airline_iata'), 'aircraftstates', ['airline_iata'], unique=False)
    op.create_index(op.f('ix_aircraftstates_airline_icao'), 'aircraftstates', ['airline_icao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircraftstates_airline_icao'), table_name='aircraftstates')
    op.drop_index(op.f('ix_aircraftstates_airline_iata'), table_name='aircraftstates')
    op.drop_table('aircraftstates')
    op.drop_index('ix_snapshots_updated', table_name='flightsnapshots')
    op.drop_index('ix_snapshots_reg_updated', table_name='flightsnapshots')
    op.drop_index('ix_snapshots_reg_status', table_name='flightsnapshots')
    op.drop_index('ix_snapshots_reg_number', table_name='flightsnapshots')
    op.drop_index('ix_snapshots_airline_icao', table_name='flightsnapshots')
    op.drop_index('ix_snapshots_airline_iata', table_name='flightsnapshots')
    op.drop_table('flightsnapshots')
    # ### end Alembic commands ###
