"""fix airline nullable

Revision ID: 6fed5e7e39df
Revises: b50824f13759
Create Date: 2026-01-07 19:28:24.068057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fed5e7e39df'
down_revision: Union[str, Sequence[str], None] = 'b50824f13759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraftstates', 'airline_icao',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('aircraftstates', 'airline_iata',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraftstates', 'airline_iata',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('aircraftstates', 'airline_icao',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###
