"""fix nullable

Revision ID: 71e07d5d60f6
Revises: 32bd7407cf45
Create Date: 2026-01-07 19:38:40.662679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e07d5d60f6'
down_revision: Union[str, Sequence[str], None] = '32bd7407cf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_aircraftstates_reg_number'), 'aircraftstates', ['reg_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircraftstates_reg_number'), table_name='aircraftstates')
    # ### end Alembic commands ###
