"""add field TYPE

Revision ID: b50824f13759
Revises: 57fc7b967bb7
Create Date: 2026-01-07 19:16:31.566466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50824f13759'
down_revision: Union[str, Sequence[str], None] = '57fc7b967bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flightsnapshots', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flightsnapshots', 'type')
    # ### end Alembic commands ###
