"""fix uniq constraint

Revision ID: 3f58ed514a36
Revises: c525b823f591
Create Date: 2026-05-14 15:56:26.390468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f58ed514a36'
down_revision: Union[str, Sequence[str], None] = 'c525b823f591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_historical_schedule_unique_flight', 'historicalschedules', ['type', 'departure_scheduled_time', 'departure_iata_code', 'arrival_iata_code', 'flight_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_historical_schedule_unique_flight', 'historicalschedules', type_='unique')
    # ### end Alembic commands ###
