"""fix uniq constaint

Revision ID: 44eaf1dbf931
Revises: fc390e2cf478
Create Date: 2026-05-13 17:06:01.292859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44eaf1dbf931'
down_revision: Union[str, Sequence[str], None] = 'fc390e2cf478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_historical_schedule_unique_flight', 'historicalschedules', ['type', 'departure_scheduled_time', 'departure_iata_code', 'arrival_iata_code', 'flight_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_historical_schedule_unique_flight', 'historicalschedules', type_='unique')
    # ### end Alembic commands ###
