"""fix uniq constraint

Revision ID: c525b823f591
Revises: 44eaf1dbf931
Create Date: 2026-05-13 17:07:42.023500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c525b823f591'
down_revision: Union[str, Sequence[str], None] = '44eaf1dbf931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historicalschedules_flight_iata_number'), table_name='historicalschedules')
    op.create_index(op.f('ix_historicalschedules_flight_iata_number'), 'historicalschedules', ['flight_iata_number'], unique=False)
    op.drop_index(op.f('ix_historicalschedules_flight_icao_number'), table_name='historicalschedules')
    op.create_index(op.f('ix_historicalschedules_flight_icao_number'), 'historicalschedules', ['flight_icao_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historicalschedules_flight_icao_number'), table_name='historicalschedules')
    op.create_index(op.f('ix_historicalschedules_flight_icao_number'), 'historicalschedules', ['flight_icao_number'], unique=True)
    op.drop_index(op.f('ix_historicalschedules_flight_iata_number'), table_name='historicalschedules')
    op.create_index(op.f('ix_historicalschedules_flight_iata_number'), 'historicalschedules', ['flight_iata_number'], unique=True)
    # ### end Alembic commands ###
