"""init

Revision ID: fc390e2cf478
Revises: 
Create Date: 2026-05-13 16:21:31.362103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc390e2cf478'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicalschedules',
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('departure_iata_code', sa.String(), nullable=True),
    sa.Column('departure_icao_code', sa.String(), nullable=True),
    sa.Column('departure_terminal', sa.String(), nullable=True),
    sa.Column('departure_gate', sa.String(), nullable=True),
    sa.Column('departure_delay', sa.Integer(), nullable=True),
    sa.Column('departure_scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_estimated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_actual_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_estimated_runway', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_actual_runway', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_iata_code', sa.String(), nullable=True),
    sa.Column('arrival_icao_code', sa.String(), nullable=True),
    sa.Column('arrival_terminal', sa.String(), nullable=True),
    sa.Column('arrival_baggage', sa.String(), nullable=True),
    sa.Column('arrival_gate', sa.String(), nullable=True),
    sa.Column('arrival_delay', sa.Integer(), nullable=True),
    sa.Column('arrival_scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_estimated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_actual_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_estimated_runway', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_actual_runway', sa.DateTime(timezone=True), nullable=True),
    sa.Column('airline_name', sa.String(), nullable=True),
    sa.Column('airline_iata_code', sa.String(), nullable=True),
    sa.Column('airline_icao_code', sa.String(), nullable=True),
    sa.Column('flight_number', sa.String(), nullable=True),
    sa.Column('flight_iata_number', sa.String(), nullable=True),
    sa.Column('flight_icao_number', sa.String(), nullable=True),
    sa.Column('codeshared_airline_name', sa.String(), nullable=True),
    sa.Column('codeshared_airline_iata_code', sa.String(), nullable=True),
    sa.Column('codeshared_airline_icao_code', sa.String(), nullable=True),
    sa.Column('codeshared_flight_number', sa.String(), nullable=True),
    sa.Column('codeshared_flight_iata_number', sa.String(), nullable=True),
    sa.Column('codeshared_flight_icao_number', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicalschedules_airline_iata_code'), 'historicalschedules', ['airline_iata_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_airline_icao_code'), 'historicalschedules', ['airline_icao_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_arrival_iata_code'), 'historicalschedules', ['arrival_iata_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_arrival_icao_code'), 'historicalschedules', ['arrival_icao_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_codeshared_airline_iata_code'), 'historicalschedules', ['codeshared_airline_iata_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_codeshared_airline_icao_code'), 'historicalschedules', ['codeshared_airline_icao_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_codeshared_flight_iata_number'), 'historicalschedules', ['codeshared_flight_iata_number'], unique=False)
    op.create_index(op.f('ix_historicalschedules_codeshared_flight_icao_number'), 'historicalschedules', ['codeshared_flight_icao_number'], unique=False)
    op.create_index(op.f('ix_historicalschedules_departure_iata_code'), 'historicalschedules', ['departure_iata_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_departure_icao_code'), 'historicalschedules', ['departure_icao_code'], unique=False)
    op.create_index(op.f('ix_historicalschedules_flight_iata_number'), 'historicalschedules', ['flight_iata_number'], unique=True)
    op.create_index(op.f('ix_historicalschedules_flight_icao_number'), 'historicalschedules', ['flight_icao_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historicalschedules_flight_icao_number'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_flight_iata_number'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_departure_icao_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_departure_iata_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_codeshared_flight_icao_number'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_codeshared_flight_iata_number'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_codeshared_airline_icao_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_codeshared_airline_iata_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_arrival_icao_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_arrival_iata_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_airline_icao_code'), table_name='historicalschedules')
    op.drop_index(op.f('ix_historicalschedules_airline_iata_code'), table_name='historicalschedules')
    op.drop_table('historicalschedules')
    # ### end Alembic commands ###
