"""add airports and runways tables

Revision ID: 4913ec903643
Revises: 5847bd48714c
Create Date: 2026-01-28 17:18:12.185597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4913ec903643'
down_revision: Union[str, Sequence[str], None] = '5847bd48714c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('icao', sa.String(length=4), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('timezone_name', sa.String(), nullable=False),
    sa.Column('timezone_offset', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airport_iata'), 'airport', ['iata'], unique=False)
    op.create_index(op.f('ix_airport_icao'), 'airport', ['icao'], unique=False)
    op.create_table('airportrunway',
    sa.Column('airport_id', sa.BigInteger(), nullable=False),
    sa.Column('designator', sa.String(), nullable=False),
    sa.Column('heading', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('thr_lat', sa.Float(), nullable=False),
    sa.Column('thr_lon', sa.Float(), nullable=False),
    sa.Column('surface_type', sa.String(), nullable=False),
    sa.Column('surface_description', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airportrunway_airport_id'), 'airportrunway', ['airport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airportrunway_airport_id'), table_name='airportrunway')
    op.drop_table('airportrunway')
    op.drop_index(op.f('ix_airport_icao'), table_name='airport')
    op.drop_index(op.f('ix_airport_iata'), table_name='airport')
    op.drop_table('airport')
    # ### end Alembic commands ###
