"""add time_delta column

Revision ID: 5847bd48714c
Revises: 7f36b0f64274
Create Date: 2026-01-28 12:32:53.875188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5847bd48714c'
down_revision: Union[str, Sequence[str], None] = '7f36b0f64274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liveposition', sa.Column('time_delta', sa.Interval(), server_default=sa.text("INTERVAL '0'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liveposition', 'time_delta')
    # ### end Alembic commands ###
