"""add distance column

Revision ID: 9c6a21052b39
Revises: a5b58066c637
Create Date: 2026-01-26 20:14:59.902150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6a21052b39'
down_revision: Union[str, Sequence[str], None] = 'a5b58066c637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liveposition', sa.Column('actual_distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liveposition', 'actual_distance')
    # ### end Alembic commands ###
