"""init

Revision ID: a5b58066c637
Revises: 
Create Date: 2026-01-12 12:33:02.155671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b58066c637'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flightsummaries',
    sa.Column('fr24_id', sa.String(), nullable=True),
    sa.Column('flight', sa.String(), nullable=True),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('operating_as', sa.String(), nullable=True),
    sa.Column('painted_as', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reg', sa.String(), nullable=True),
    sa.Column('orig_icao', sa.String(), nullable=True),
    sa.Column('orig_iata', sa.String(), nullable=True),
    sa.Column('datetime_takeoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runway_takeoff', sa.String(), nullable=True),
    sa.Column('dest_icao', sa.String(), nullable=True),
    sa.Column('dest_iata', sa.String(), nullable=True),
    sa.Column('dest_icao_actual', sa.String(), nullable=True),
    sa.Column('dest_iata_actual', sa.String(), nullable=True),
    sa.Column('datetime_landed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runway_landed', sa.String(), nullable=True),
    sa.Column('flight_time', sa.Integer(), nullable=True),
    sa.Column('actual_distance', sa.Float(), nullable=True),
    sa.Column('circle_distance', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('hex', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_ended', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flightsummaries_dest_iata'), 'flightsummaries', ['dest_iata'], unique=False)
    op.create_index(op.f('ix_flightsummaries_dest_iata_actual'), 'flightsummaries', ['dest_iata_actual'], unique=False)
    op.create_index(op.f('ix_flightsummaries_dest_icao'), 'flightsummaries', ['dest_icao'], unique=False)
    op.create_index(op.f('ix_flightsummaries_dest_icao_actual'), 'flightsummaries', ['dest_icao_actual'], unique=False)
    op.create_index(op.f('ix_flightsummaries_operating_as'), 'flightsummaries', ['operating_as'], unique=False)
    op.create_index(op.f('ix_flightsummaries_orig_iata'), 'flightsummaries', ['orig_iata'], unique=False)
    op.create_index(op.f('ix_flightsummaries_orig_icao'), 'flightsummaries', ['orig_icao'], unique=False)
    op.create_index(op.f('ix_flightsummaries_painted_as'), 'flightsummaries', ['painted_as'], unique=False)
    op.create_index(op.f('ix_flightsummaries_reg'), 'flightsummaries', ['reg'], unique=False)
    op.create_index(op.f('ix_flightsummaries_type'), 'flightsummaries', ['type'], unique=False)
    op.create_table('liveposition',
    sa.Column('fr24_id', sa.String(), nullable=True),
    sa.Column('flight', sa.String(), nullable=True),
    sa.Column('hex', sa.String(), nullable=True),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('gspeed', sa.Float(), nullable=True),
    sa.Column('vspeed', sa.Float(), nullable=True),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('squawk', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('orig_icao', sa.String(), nullable=True),
    sa.Column('orig_iata', sa.String(), nullable=True),
    sa.Column('dest_icao', sa.String(), nullable=True),
    sa.Column('dest_iata', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reg', sa.String(), nullable=True),
    sa.Column('operating_as', sa.String(), nullable=True),
    sa.Column('painted_as', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liveposition_dest_iata'), 'liveposition', ['dest_iata'], unique=False)
    op.create_index(op.f('ix_liveposition_dest_icao'), 'liveposition', ['dest_icao'], unique=False)
    op.create_index(op.f('ix_liveposition_operating_as'), 'liveposition', ['operating_as'], unique=False)
    op.create_index(op.f('ix_liveposition_orig_iata'), 'liveposition', ['orig_iata'], unique=False)
    op.create_index(op.f('ix_liveposition_orig_icao'), 'liveposition', ['orig_icao'], unique=False)
    op.create_index(op.f('ix_liveposition_painted_as'), 'liveposition', ['painted_as'], unique=False)
    op.create_index(op.f('ix_liveposition_reg'), 'liveposition', ['reg'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liveposition_reg'), table_name='liveposition')
    op.drop_index(op.f('ix_liveposition_painted_as'), table_name='liveposition')
    op.drop_index(op.f('ix_liveposition_orig_icao'), table_name='liveposition')
    op.drop_index(op.f('ix_liveposition_orig_iata'), table_name='liveposition')
    op.drop_index(op.f('ix_liveposition_operating_as'), table_name='liveposition')
    op.drop_index(op.f('ix_liveposition_dest_icao'), table_name='liveposition')
    op.drop_index(op.f('ix_liveposition_dest_iata'), table_name='liveposition')
    op.drop_table('liveposition')
    op.drop_index(op.f('ix_flightsummaries_type'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_reg'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_painted_as'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_orig_icao'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_orig_iata'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_operating_as'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_dest_icao_actual'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_dest_icao'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_dest_iata_actual'), table_name='flightsummaries')
    op.drop_index(op.f('ix_flightsummaries_dest_iata'), table_name='flightsummaries')
    op.drop_table('flightsummaries')
    # ### end Alembic commands ###
