"""added alternative font size

Revision ID: 09d1432b11b9
Revises: aaf151680791
Create Date: 2026-05-21 11:04:41.024530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d1432b11b9'
down_revision: Union[str, Sequence[str], None] = 'aaf151680791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fonts', sa.Column('font_size_alternative', sa.Integer(), nullable=True))
    op.drop_column('fonts', 'client_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fonts', sa.Column('client_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fonts', 'font_size_alternative')
    # ### end Alembic commands ###
