"""add some tables

Revision ID: 1638c4c1b7b0
Revises: 
Create Date: 2026-05-11 13:09:34.891905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1638c4c1b7b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraftmanual',
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(), nullable=True),
    sa.Column('msn', sa.Integer(), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('mtow', sa.Integer(), nullable=True),
    sa.Column('agreed_value', sa.Float(), nullable=True),
    sa.Column('agreed_value_result', sa.Float(), nullable=True),
    sa.Column('combined_single_limit', sa.Float(), nullable=True),
    sa.Column('hsl_deductible', sa.Float(), nullable=True),
    sa.Column('hd_deductible', sa.Float(), nullable=True),
    sa.Column('depreciation_rate', sa.Float(), nullable=True),
    sa.Column('depreciation_start_date', sa.Date(), nullable=True),
    sa.Column('policy_start', sa.Date(), nullable=True),
    sa.Column('policy_end', sa.Date(), nullable=True),
    sa.Column('lessee', sa.String(), nullable=True),
    sa.Column('lessor', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraftmanual_aircraft_id'), 'aircraftmanual', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_aircraftmanual_msn'), 'aircraftmanual', ['msn'], unique=False)
    op.create_index(op.f('ix_aircraftmanual_registration'), 'aircraftmanual', ['registration'], unique=False)
    op.create_table('aircraftenginesmanual',
    sa.Column('aircraft_manual_id', sa.BigInteger(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Enum('NOSE', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'TAIL', name='enginepositionenum'), nullable=False),
    sa.Column('engine_msn', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_manual_id'], ['aircraftmanual.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraftenginesmanual_aircraft_manual_id'), 'aircraftenginesmanual', ['aircraft_manual_id'], unique=False)
    op.create_table('aircraftengines',
    sa.Column('aircraft_id', sa.BigInteger(), nullable=False),
    sa.Column('engine_id', sa.BigInteger(), nullable=False),
    sa.Column('engine_msn', sa.String(), nullable=True),
    sa.Column('position', sa.Enum('NOSE', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'TAIL', name='enginepositionenum'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraftengines_aircraft_id'), 'aircraftengines', ['aircraft_id'], unique=False)
    op.create_table('aircraftlesseelessors',
    sa.Column('aircraft_id', sa.BigInteger(), nullable=False),
    sa.Column('lessee', sa.String(), nullable=True),
    sa.Column('lessor', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraftlesseelessors_aircraft_id'), 'aircraftlesseelessors', ['aircraft_id'], unique=False)
    op.create_table('aircrafttechnicaldatas',
    sa.Column('aircraft_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source', sa.Enum('CIRIUM', 'LEASE_AGREEMENT', 'MANUAL', name='aircraftdatasourceenum'), nullable=True),
    sa.Column('data_source_row_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INSURED', 'NOT_INSURED', name='aircraftinsuredstatusenum'), nullable=False),
    sa.Column('av_fixed', sa.Boolean(), nullable=False),
    sa.Column('in_dashboard', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircrafttechnicaldatas_aircraft_id'), 'aircrafttechnicaldatas', ['aircraft_id'], unique=True)
    op.add_column('aircraft', sa.Column('mtow', sa.Integer(), nullable=True))
    op.add_column('aircraft', sa.Column('agreed_value_result', sa.Float(), nullable=True))
    op.add_column('aircraft', sa.Column('hsl_deductible', sa.Float(), nullable=True))
    op.add_column('aircraft', sa.Column('hd_deductible', sa.Float(), nullable=True))
    op.add_column('aircraft', sa.Column('depreciation_rate', sa.Float(), nullable=True))
    op.add_column('aircraft', sa.Column('depreciation_start_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_aircraft_msn'), 'aircraft', ['msn'], unique=False)
    op.create_index(op.f('ix_aircraft_registration'), 'aircraft', ['registration'], unique=False)
    op.drop_constraint(op.f('aircraft_engine_id_fkey'), 'aircraft', type_='foreignkey')
    op.drop_column('aircraft', 'status')
    op.drop_column('aircraft', 'lessor')
    op.drop_column('aircraft', 'engine_id')
    op.drop_column('aircraft', 'agreed_value_down_absolute')
    op.drop_column('aircraft', 'number_of_engines')
    op.drop_column('aircraft', 'engine2_msn')
    op.drop_column('aircraft', 'engine3_msn')
    op.drop_column('aircraft', 'in_dashboard')
    op.drop_column('aircraft', 'agreed_value_down_percent')
    op.drop_column('aircraft', 'engine1_msn')
    op.drop_column('aircraft', 'av_source')
    op.drop_column('aircraft', 'all_risks_deductible')
    op.drop_column('aircraft', 'hull_and_spares_excess')
    op.drop_column('aircraft', 'engine4_msn')
    op.drop_column('aircraft', 'lessee')
    op.add_column('aircraftpolicies', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_aircraftpolicies_aircraft_id'), 'aircraftpolicies', ['aircraft_id'], unique=False)
    op.drop_constraint(op.f('aircrafttemplates_asset_id_key'), 'aircrafttemplates', type_='unique')
    op.create_index(op.f('ix_aircrafttemplates_asset_id'), 'aircrafttemplates', ['asset_id'], unique=True)
    op.create_index(op.f('ix_aircrafttemplates_template_name'), 'aircrafttemplates', ['template_name'], unique=False)
    op.drop_constraint(op.f('engines_engine_model_key'), 'engines', type_='unique')
    op.create_index(op.f('ix_engines_engine_model'), 'engines', ['engine_model'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engines_engine_model'), table_name='engines')
    op.create_unique_constraint(op.f('engines_engine_model_key'), 'engines', ['engine_model'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_aircrafttemplates_template_name'), table_name='aircrafttemplates')
    op.drop_index(op.f('ix_aircrafttemplates_asset_id'), table_name='aircrafttemplates')
    op.create_unique_constraint(op.f('aircrafttemplates_asset_id_key'), 'aircrafttemplates', ['asset_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_aircraftpolicies_aircraft_id'), table_name='aircraftpolicies')
    op.drop_column('aircraftpolicies', 'active')
    op.add_column('aircraft', sa.Column('lessee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('engine4_msn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('hull_and_spares_excess', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('all_risks_deductible', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('av_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('engine1_msn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('agreed_value_down_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('in_dashboard', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('aircraft', sa.Column('engine3_msn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('engine2_msn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('number_of_engines', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('agreed_value_down_absolute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('engine_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('lessor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('aircraft_engine_id_fkey'), 'aircraft', 'engines', ['engine_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_aircraft_registration'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_msn'), table_name='aircraft')
    op.drop_column('aircraft', 'depreciation_start_date')
    op.drop_column('aircraft', 'depreciation_rate')
    op.drop_column('aircraft', 'hd_deductible')
    op.drop_column('aircraft', 'hsl_deductible')
    op.drop_column('aircraft', 'agreed_value_result')
    op.drop_column('aircraft', 'mtow')
    op.drop_index(op.f('ix_aircrafttechnicaldatas_aircraft_id'), table_name='aircrafttechnicaldatas')
    op.drop_table('aircrafttechnicaldatas')
    op.drop_index(op.f('ix_aircraftlesseelessors_aircraft_id'), table_name='aircraftlesseelessors')
    op.drop_table('aircraftlesseelessors')
    op.drop_index(op.f('ix_aircraftengines_aircraft_id'), table_name='aircraftengines')
    op.drop_table('aircraftengines')
    op.drop_index(op.f('ix_aircraftenginesmanual_aircraft_manual_id'), table_name='aircraftenginesmanual')
    op.drop_table('aircraftenginesmanual')
    op.drop_index(op.f('ix_aircraftmanual_registration'), table_name='aircraftmanual')
    op.drop_index(op.f('ix_aircraftmanual_msn'), table_name='aircraftmanual')
    op.drop_index(op.f('ix_aircraftmanual_aircraft_id'), table_name='aircraftmanual')
    op.drop_table('aircraftmanual')
    # ### end Alembic commands ###
