"""fix aircraft not null bug

Revision ID: 6a369e9306e7
Revises: 1638c4c1b7b0
Create Date: 2026-05-12 02:26:41.572523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a369e9306e7'
down_revision: Union[str, Sequence[str], None] = '1638c4c1b7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'airline_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('aircraft', 'template_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'template_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('aircraft', 'airline_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
