"""added iata column to airlines

Revision ID: 6c81d0247b7f
Revises: 9f64b61587ad
Create Date: 2026-05-20 12:00:50.964125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c81d0247b7f'
down_revision: Union[str, Sequence[str], None] = '9f64b61587ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airlines', sa.Column('iata', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airlines', 'iata')
    # ### end Alembic commands ###
