"""added columns to manual aircraft

Revision ID: 6de3803d198c
Revises: 6a369e9306e7
Create Date: 2026-05-15 11:04:15.999188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de3803d198c'
down_revision: Union[str, Sequence[str], None] = '6a369e9306e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraftmanual', sa.Column('data_source', sa.Enum('CIRIUM', 'LEASE_AGREEMENT', 'MANUAL', name='aircraftdatasourceenum'), nullable=True))
    op.add_column('aircraftmanual', sa.Column('status', sa.Enum('INSURED', 'NOT_INSURED', name='aircraftinsuredstatusenum'), nullable=False))
    op.add_column('aircraftmanual', sa.Column('av_fixed', sa.Boolean(), nullable=False))
    op.add_column('aircraftmanual', sa.Column('in_dashboard', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraftmanual', 'in_dashboard')
    op.drop_column('aircraftmanual', 'av_fixed')
    op.drop_column('aircraftmanual', 'status')
    op.drop_column('aircraftmanual', 'data_source')
    # ### end Alembic commands ###
