"""added appearance tables

Revision ID: 843f8bcb2af0
Revises: 09d1432b11b9
Create Date: 2026-05-21 12:27:17.914830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843f8bcb2af0'
down_revision: Union[str, Sequence[str], None] = '09d1432b11b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicationappearances',
    sa.Column('appearance', sa.Enum('DARK', 'LIGHT', name='appearanceenum'), nullable=False),
    sa.Column('main_color', sa.String(), nullable=False),
    sa.Column('secondary_color', sa.String(), nullable=False),
    sa.Column('app_color', sa.String(), nullable=False),
    sa.Column('background_color', sa.String(), nullable=False),
    sa.Column('field_color', sa.String(), nullable=False),
    sa.Column('button_color', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationappearances_appearance'), 'applicationappearances', ['appearance'], unique=False)
    op.create_table('userdevicesettings',
    sa.Column('os_type', sa.Enum('WINDOWS', 'ANDROID', 'IOS', 'LINUX', 'MACOS', name='ostypeenum'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appearance_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appearance_id'], ['applicationappearances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'os_type', name='uq_user_device_os_type')
    )
    op.create_index(op.f('ix_userdevicesettings_user_id'), 'userdevicesettings', ['user_id'], unique=False)
    op.add_column('fonts', sa.Column('font_color_alternative', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fonts', 'font_color_alternative')
    op.drop_index(op.f('ix_userdevicesettings_user_id'), table_name='userdevicesettings')
    op.drop_table('userdevicesettings')
    op.drop_index(op.f('ix_applicationappearances_appearance'), table_name='applicationappearances')
    op.drop_table('applicationappearances')
    # ### end Alembic commands ###
