"""update aircraft_id manual Nullable=True

Revision ID: 92eb4c597cb5
Revises: 6c81d0247b7f
Create Date: 2026-05-21 00:26:56.606648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92eb4c597cb5'
down_revision: Union[str, Sequence[str], None] = '6c81d0247b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraftmanual', 'aircraft_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('airline_name_trgm_idx'), table_name='airlines', postgresql_ops={'airline_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('engine_manufacture_trgm_idx'), table_name='engines', postgresql_ops={'engine_manufacture': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('engine_model_trgm_idx'), table_name='engines', postgresql_ops={'engine_model': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('engine_model_trgm_idx'), 'engines', ['engine_model'], unique=False, postgresql_ops={'engine_model': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('engine_manufacture_trgm_idx'), 'engines', ['engine_manufacture'], unique=False, postgresql_ops={'engine_manufacture': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('airline_name_trgm_idx'), 'airlines', ['airline_name'], unique=False, postgresql_ops={'airline_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('aircraftmanual', 'aircraft_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
