"""fixed airline nullable icao

Revision ID: 9f64b61587ad
Revises: be0d343cb569
Create Date: 2026-05-20 11:56:13.923181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f64b61587ad'
down_revision: Union[str, Sequence[str], None] = 'be0d343cb569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airlines', 'icao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airlines', 'icao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
