"""added tgrm indexes

Revision ID: aaf151680791
Revises: 92eb4c597cb5
Create Date: 2026-05-21 09:04:46.089691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf151680791'
down_revision: Union[str, Sequence[str], None] = '92eb4c597cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('airline_name_trgm_idx', 'airlines', ['airline_name'], unique=False, postgresql_using='gin', postgresql_ops={'airline_name': 'gin_trgm_ops'})
    op.create_index('engine_manufacture_trgm_idx', 'engines', ['engine_manufacture'], unique=False, postgresql_using='gin', postgresql_ops={'engine_manufacture': 'gin_trgm_ops'})
    op.create_index('engine_model_trgm_idx', 'engines', ['engine_model'], unique=False, postgresql_using='gin', postgresql_ops={'engine_model': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('engine_model_trgm_idx', table_name='engines', postgresql_using='gin', postgresql_ops={'engine_model': 'gin_trgm_ops'})
    op.drop_index('engine_manufacture_trgm_idx', table_name='engines', postgresql_using='gin', postgresql_ops={'engine_manufacture': 'gin_trgm_ops'})
    op.drop_index('airline_name_trgm_idx', table_name='airlines', postgresql_using='gin', postgresql_ops={'airline_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
