"""added columns to fonts

Revision ID: be0d343cb569
Revises: 6de3803d198c
Create Date: 2026-05-16 14:44:30.541355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0d343cb569'
down_revision: Union[str, Sequence[str], None] = '6de3803d198c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fonts', sa.Column('client_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fonts', 'client_type')
    # ### end Alembic commands ###
