"""update appearance name

Revision ID: cd7845ec5605
Revises: 843f8bcb2af0
Create Date: 2026-05-21 14:13:51.035202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd7845ec5605'
down_revision: Union[str, Sequence[str], None] = '843f8bcb2af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationappearances', sa.Column('appearance_type', sa.Enum('LIGHT', 'DARK', name='appearanceenum'), nullable=False))
    op.drop_index(op.f('ix_applicationappearances_appearance'), table_name='applicationappearances')
    op.create_index(op.f('ix_applicationappearances_appearance_type'), 'applicationappearances', ['appearance_type'], unique=False)
    op.drop_column('applicationappearances', 'appearance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationappearances', sa.Column('appearance', postgresql.ENUM('DARK', 'LIGHT', name='appearanceenum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_applicationappearances_appearance_type'), table_name='applicationappearances')
    op.create_index(op.f('ix_applicationappearances_appearance'), 'applicationappearances', ['appearance'], unique=False)
    op.drop_column('applicationappearances', 'appearance_type')
    # ### end Alembic commands ###
