"""initial service tables

Revision ID: 15c04fcc26cf
Revises: 
Create Date: 2026-06-27 22:33:43.206880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15c04fcc26cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_tokens_token_prefix'), 'api_tokens', ['token_prefix'], unique=True)
    op.create_table('job_statuses',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_statuses_job_id'), 'job_statuses', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_statuses_kind'), 'job_statuses', ['kind'], unique=False)
    op.create_index('ix_job_statuses_kind_state', 'job_statuses', ['kind', 'state'], unique=False)
    op.create_index(op.f('ix_job_statuses_state'), 'job_statuses', ['state'], unique=False)
    op.create_table('schedule_registry',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('queue', sa.String(length=64), nullable=False),
    sa.Column('func_name', sa.String(length=128), nullable=False),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('run_now', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_registry_name'), 'schedule_registry', ['name'], unique=True)
    op.create_index(op.f('ix_schedule_registry_next_run_at'), 'schedule_registry', ['next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_registry_next_run_at'), table_name='schedule_registry')
    op.drop_index(op.f('ix_schedule_registry_name'), table_name='schedule_registry')
    op.drop_table('schedule_registry')
    op.drop_index(op.f('ix_job_statuses_state'), table_name='job_statuses')
    op.drop_index('ix_job_statuses_kind_state', table_name='job_statuses')
    op.drop_index(op.f('ix_job_statuses_kind'), table_name='job_statuses')
    op.drop_index(op.f('ix_job_statuses_job_id'), table_name='job_statuses')
    op.drop_table('job_statuses')
    op.drop_index(op.f('ix_api_tokens_token_prefix'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
