"""update ivfflat

Revision ID: 20403473fd30
Revises: 911dd1c1a488
Create Date: 2025-12-24 02:10:38.057307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20403473fd30'
down_revision: Union[str, Sequence[str], None] = '911dd1c1a488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_embedding_ivf'), table_name='documentembeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('globalembeddings', sa.Column('text_hash', sa.UUID(), sa.Computed('md5(text)::uuid', persisted=True), nullable=False))
    op.drop_index(op.f('idx_global_embedding_ivf'), table_name='globalembeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_global_embedding'), table_name='globalembeddings')
    op.drop_constraint(op.f('uq_global_chunk'), 'globalembeddings', type_='unique')
    op.create_unique_constraint(None, 'globalembeddings', ['text_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'globalembeddings', type_='unique')
    op.create_unique_constraint(op.f('uq_global_chunk'), 'globalembeddings', ['text', 'embedding'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_global_embedding'), 'globalembeddings', ['embedding'], unique=False)
    op.create_index(op.f('idx_global_embedding_ivf'), 'globalembeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('globalembeddings', 'text_hash')
    op.create_index(op.f('idx_document_embedding_ivf'), 'documentembeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
