"""update pbi request summary

Revision ID: 3f2c57bd6c84
Revises: e36bdde697bd
Create Date: 2026-02-27 15:54:41.224763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2c57bd6c84'
down_revision: Union[str, Sequence[str], None] = 'e36bdde697bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pbirequestfrsummarydatas', sa.Column('estimate_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pbirequestfrsummarydatas', 'estimate_time')
    # ### end Alembic commands ###
