"""update ivfflat

Revision ID: 911dd1c1a488
Revises: 76d722c63046
Create Date: 2025-12-24 00:04:18.459464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
# revision identifiers, used by Alembic.
revision: str = '911dd1c1a488'
down_revision: Union[str, Sequence[str], None] = '76d722c63046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentembeddings',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name', 'chunk_index', name='uq_document_chunk')
    )
    op.create_index('ix_document_file_name', 'documentembeddings', ['file_name'], unique=False)
    op.create_index(op.f('ix_documentembeddings_file_name'), 'documentembeddings', ['file_name'], unique=False)
    op.create_table('globalembeddings',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'embedding', name='uq_global_chunk')
    )
    op.create_index('ix_global_embedding', 'globalembeddings', ['embedding'], unique=False)
    op.alter_column('fieldsynonyms', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(),
               nullable=False)
    op.drop_index(op.f('ix_fieldsynonyms_field_name'), table_name='fieldsynonyms')
    op.create_index('ix_field_synonym_field_name', 'fieldsynonyms', ['field_name'], unique=False)
    op.create_unique_constraint('uq_field_synonym', 'fieldsynonyms', ['field_name', 'synonym'])
    op.create_index(
        "idx_document_embedding_ivf",
        "documentembeddings",
        ["embedding"],
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100}
    )
    op.create_index(
        "idx_global_embedding_ivf",
        "globalembeddings",
        ["embedding"],
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100}
    )
    op.execute("ANALYZE documentembeddings;")
    op.execute("ANALYZE globalembeddings;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_field_synonym', 'fieldsynonyms', type_='unique')
    op.drop_index('ix_field_synonym_field_name', table_name='fieldsynonyms')
    op.create_index(op.f('ix_fieldsynonyms_field_name'), 'fieldsynonyms', ['field_name'], unique=False)
    op.alter_column('fieldsynonyms', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(),
               nullable=True)
    op.drop_index('ix_global_embedding', table_name='globalembeddings')
    op.drop_table('globalembeddings')
    op.drop_index(op.f('ix_documentembeddings_file_name'), table_name='documentembeddings')
    op.drop_index('ix_document_file_name', table_name='documentembeddings')
    op.drop_table('documentembeddings')
    # ### end Alembic commands ###
